/* The mod loader: a stand-in dinput8.dll. Put it next to SheepD3D.exe. The game imports one function from DINPUT8.dll,
 * DirectInput8Create, which this DLL forwards to the system's own dinput8.dll; Windows loads a DLL from the game's
 * folder before the system copy, so the loader runs inside the player's own, unmodified SheepD3D.exe.
 *
 * At process start (DllMain) it checks the exe by its SHA-1 and, if it is the PAL SheepD3D.exe (whose functions are at
 * the addresses in data/symbols*.csv, as this project's byte-identical build proves), hooks WinMain. When WinMain runs,
 * it loads every Mods\<Name>\<Name>.dll, calls its SdwModInit with the API (mods/kit/sdw_mod.h), and starts the game.
 * Everything it does is written to Mods\mods.log. With any other exe it only forwards DirectInput8Create. */
#include <windows.h>
#include <wincrypt.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "hook.h"
#include "levelpatch.h"
#include "../kit/sdw_mod.h"

typedef struct {
    const char *name;
    unsigned addr;
} SdwSymbol;
extern const SdwSymbol g_sdwSymbols[]; /* symbols.c, generated by tools/build_mods.py, sorted by name */
extern const int g_sdwSymbolCount;
extern const LevelPatchProp g_sdwProps[];
extern const unsigned short g_sdwClassSounds[][2];
extern const int g_sdwClassSoundCount;
extern const unsigned short g_sdwClassPictures[][2];
extern const int g_sdwClassPictureCount; /* symbols.c too: every class's property names, from scenaric_props.h */
extern const int g_sdwPropCount;

#define MAX_CALLBACKS 64

static FILE *g_log;
static char g_gameDir[MAX_PATH];
static char g_currentMod[64];
static const char *g_gameName;
static SdwEventFn g_onFrame[MAX_CALLBACKS], g_onLoad[MAX_CALLBACKS], g_onFree[MAX_CALLBACKS];
static SdwObjectFn g_onObject[MAX_CALLBACKS];
static int g_nFrame, g_nLoad, g_nFree, g_nObject;
static char g_modDirs[64][MAX_PATH], g_modNames[64][64]; /* the loaded mods, in load order */
static int g_nMods;

/* ---------------------------------------------------------------------------------------------------------- log */

static void log_line(const char *fmt, ...)
{
    va_list ap;
    SYSTEMTIME t;
    if (!g_log)
        return;
    GetLocalTime(&t);
    fprintf(g_log, "%02d:%02d:%02d ", t.wHour, t.wMinute, t.wSecond);
    if (g_currentMod[0])
        fprintf(g_log, "[%s] ", g_currentMod);
    va_start(ap, fmt);
    vfprintf(g_log, fmt, ap);
    va_end(ap);
    fputc('\n', g_log);
    fflush(g_log);
}

/* ---------------------------------------------------------------------------------------------------------- the exe */

static int sha1_file(const char *path, char out[41])
{
    HCRYPTPROV prov = 0;
    HCRYPTHASH hash = 0;
    BYTE buf[65536], digest[20];
    DWORD got, len = sizeof digest;
    HANDLE f = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, 0, OPEN_EXISTING, 0, 0);
    int i, ok = 0;
    if (f == INVALID_HANDLE_VALUE)
        return 0;
    if (CryptAcquireContextA(&prov, 0, 0, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT) &&
        CryptCreateHash(prov, CALG_SHA1, 0, 0, &hash)) {
        ok = 1;
        while (ReadFile(f, buf, sizeof buf, &got, 0) && got)
            ok &= CryptHashData(hash, buf, got, 0) != 0;
        ok &= CryptGetHashParam(hash, HP_HASHVAL, digest, &len, 0) != 0;
    }
    if (hash)
        CryptDestroyHash(hash);
    if (prov)
        CryptReleaseContext(prov, 0);
    CloseHandle(f);
    for (i = 0; ok && i < 20; i++)
        sprintf(out + 2 * i, "%02x", digest[i]);
    return ok;
}

/* ---------------------------------------------------------------------------------------------------------- API */

/* An exe built from the source with changes (tools/build_fixed.py) has its functions and data at other addresses. Its
 * symbol file, <exe>.sdwsym beside it, gives them: "SDW symbols, SHA-1 <its hash>", then per line an original address
 * and that thing's address in this exe, sorted (the build writes it from the two builds' linker maps). Every address
 * of the symbol table goes through it; one it lacks is not in this exe. */
static unsigned (*g_translate)[2];
static int g_nTranslate;
static char *read_text(const char *path);

static int load_translation(const char *exe, const char *sha)
{
    char path[MAX_PATH], *text, *s, *dot;
    int n = 0, cap = 0;
    lstrcpynA(path, exe, sizeof path - 8);
    dot = strrchr(path, '.');
    if (dot && !strchr(dot, '\\'))
        *dot = 0;
    strcat(path, ".sdwsym");
    if (!(text = read_text(path))) {
        log_line("no symbol file %s", path);
        return 0;
    }
    s = strstr(text, "SHA-1 ");
    if (!s || strncmp(s + 6, sha, 40)) {
        log_line("%s is for another exe", path);
        free(text);
        return 0;
    }
    for (s = strchr(s, '\n'); s && *++s;) {
        unsigned a, b;
        if (sscanf(s, "%x %x", &a, &b) == 2) {
            if (n == cap) {
                void *grown = realloc(g_translate, (cap = cap ? cap * 2 : 4096) * sizeof *g_translate);
                if (!grown)
                    break;
                g_translate = (unsigned (*)[2])grown;
            }
            g_translate[n][0] = a;
            g_translate[n++][1] = b;
        }
        s = strchr(s, '\n');
        if (!s)
            break;
    }
    free(text);
    g_nTranslate = n;
    log_line("its symbol file: %d addresses (%s)", n, path);
    return n > 0;
}

static unsigned translate(unsigned addr)
{
    int lo = 0, hi = g_nTranslate - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (g_translate[mid][0] == addr)
            return g_translate[mid][1];
        if (g_translate[mid][0] < addr)
            lo = mid + 1;
        else
            hi = mid - 1;
    }
    return 0;
}

static void *api_find(const char *name)
{
    int lo = 0, hi = g_sdwSymbolCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2, c = strcmp(name, g_sdwSymbols[mid].name);
        if (!c && g_translate)
            return (void *)(size_t)translate(g_sdwSymbols[mid].addr);
        if (!c)
            return (void *)(size_t)g_sdwSymbols[mid].addr;
        if (c < 0)
            hi = mid - 1;
        else
            lo = mid + 1;
    }
    return 0;
}

/* which mod hooked what (a conflict report when two mods hook the same function: the later one runs first) */
static struct {
    void *target;
    char mod[64];
} g_hooked[256];
static int g_nHooked;

static int api_hook_address(void *target, void *replacement, void **original)
{
    char why[160];
    int r = hook_install(target, replacement, original, why, sizeof why), i;
    if (r) {
        log_line("hook at %p failed: %s", target, why);
        return r;
    }
    for (i = 0; i < g_nHooked; i++)
        if (g_hooked[i].target == target && strcmp(g_hooked[i].mod, g_currentMod))
            log_line("conflict: %p is hooked by %s too (%s runs first, then calls through to %s)", target,
                     g_hooked[i].mod, g_currentMod[0] ? g_currentMod : "the loader", g_hooked[i].mod);
    if (g_nHooked < 256) {
        g_hooked[g_nHooked].target = target;
        lstrcpynA(g_hooked[g_nHooked++].mod, g_currentMod[0] ? g_currentMod : "the loader", sizeof g_hooked[0].mod);
    }
    return 0;
}

static int api_hook(const char *name, void *replacement, void **original)
{
    void *target = api_find(name);
    int r;
    if (!target) {
        log_line("hook %s: no such name in the symbol tables", name);
        return -1;
    }
    r = api_hook_address(target, replacement, original);
    if (!r)
        log_line("hooked %s (%p)", name, target);
    return r;
}

/* the game's functions behind the events, hooked the first time a mod asks for the event */
static void (*orig_Time_Update)(void);
static void (*orig_Game_ReloadLevel)(void);
static void (*orig_Game_FreeLevel)(void);
static void *(*orig_Install_ScenaricResource)(unsigned);

static void ev_Time_Update(void)
{
    int i;
    orig_Time_Update();
    for (i = 0; i < g_nFrame; i++)
        g_onFrame[i]();
}
static void ev_Game_ReloadLevel(void)
{
    int i;
    orig_Game_ReloadLevel();
    for (i = 0; i < g_nLoad; i++)
        g_onLoad[i]();
}
static void ev_Game_FreeLevel(void)
{
    int i;
    for (i = 0; i < g_nFree; i++)
        g_onFree[i]();
    orig_Game_FreeLevel();
}
static void *ev_Install_ScenaricResource(unsigned index)
{
    int i;
    void *obj = orig_Install_ScenaricResource(index);
    if (obj)
        for (i = 0; i < g_nObject; i++)
            g_onObject[i](obj);
    return obj;
}

#define EVENT(fnname, arr, count, type, gamefn)                                               \
    static void fnname(type fn)                                                               \
    {                                                                                         \
        if (!count && api_hook(#gamefn, (void *)ev_##gamefn, (void **)&orig_##gamefn) != 0) { \
            log_line("event unavailable: " #gamefn " could not be hooked");                   \
            return;                                                                           \
        }                                                                                     \
        if (count < MAX_CALLBACKS)                                                            \
            arr[count++] = fn;                                                                \
    }
EVENT(api_on_frame, g_onFrame, g_nFrame, SdwEventFn, Time_Update)
EVENT(api_on_level_load, g_onLoad, g_nLoad, SdwEventFn, Game_ReloadLevel)
EVENT(api_on_level_free, g_onFree, g_nFree, SdwEventFn, Game_FreeLevel)
EVENT(api_on_object_created, g_onObject, g_nObject, SdwObjectFn, Install_ScenaricResource)

/* mod classes, registered again after every Scenaric_RegisterAllClasses (the game clears its registry on each load) */
typedef struct {
    SdwFactoryFn factory;
    void *iconA, *iconB;
    unsigned classFlags;
} ClassEntry; /* g_scenaricClassRegistry[200], 16 bytes each */
static struct {
    unsigned short id, like;
    SdwFactoryFn factory;
    char mod[64];
} g_classes[64];
static int g_nClasses;

static void bring_icons_and_text(ClassEntry *reg);

/* each class's two icon ids, as the game registers them (Scenaric_RegisterClass_2), for bringing an icon from
 * another level's .DAV */
static unsigned short g_iconIds[200][2];
static void(__cdecl *orig_Scenaric_RegisterClass_2)(unsigned short, void *, unsigned, unsigned short, unsigned short);
static void __cdecl ev_Scenaric_RegisterClass_2(unsigned short classId, void *factory, unsigned flags,
                                                unsigned short iconA, unsigned short iconB)
{
    if (classId < 200) {
        g_iconIds[classId][0] = iconA;
        g_iconIds[classId][1] = iconB;
    }
    orig_Scenaric_RegisterClass_2(classId, factory, flags, iconA, iconB);
}

static void(__cdecl *orig_Scenaric_RegisterAllClasses)(void);
static void __cdecl ev_Scenaric_RegisterAllClasses(void)
{
    ClassEntry *reg = (ClassEntry *)api_find("g_scenaricClassRegistry");
    int i;
    orig_Scenaric_RegisterAllClasses();
    if (reg)
        bring_icons_and_text(reg);
    for (i = 0; reg && i < g_nClasses; i++) {
        ClassEntry *e = &reg[g_classes[i].id];
        if (e->factory && e->factory != g_classes[i].factory) {
            lstrcpynA(g_currentMod, g_classes[i].mod, sizeof g_currentMod);
            log_line("class %u is the game's own: not replaced", g_classes[i].id);
            g_currentMod[0] = 0;
            continue;
        }
        *e = reg[g_classes[i].like];
        e->factory = g_classes[i].factory;
    }
}

static int hook_register_all(void) /* once */
{
    static int done, r;
    if (!done) {
        done = 1;
        r = api_hook("Scenaric_RegisterAllClasses", (void *)ev_Scenaric_RegisterAllClasses,
                     (void **)&orig_Scenaric_RegisterAllClasses);
    }
    return r;
}

static int api_register_class(unsigned short classId, SdwFactoryFn factory, unsigned short likeClassId)
{
    int i;
    if (classId >= 200 || likeClassId >= 200 || !factory || g_nClasses >= 64) {
        log_line("register_class %u: out of range (0-199)", classId);
        return -1;
    }
    for (i = 0; i < g_nClasses; i++)
        if (g_classes[i].id == classId)
            log_line("conflict: class %u is %s's too: this mod's factory is used", classId, g_classes[i].mod);
    if (hook_register_all() != 0)
        return -1;
    g_classes[g_nClasses].id = classId;
    g_classes[g_nClasses].like = likeClassId;
    g_classes[g_nClasses].factory = factory;
    lstrcpynA(g_classes[g_nClasses].mod, g_currentMod, sizeof g_classes[g_nClasses].mod);
    g_nClasses++;
    log_line("class %u registered (like class %u)", classId, likeClassId);
    return 0;
}

/* the game's Scenaric_CreateObject: the class's factory, or for a class without one (static scenery, class 12, among
 * others) the generic object its model type calls for */
static void *api_create_object(unsigned short classId, void *record)
{
    void *(__cdecl * create)(unsigned short, void *) =
        (void *(__cdecl *)(unsigned short, void *))api_find("Scenaric_CreateObject");
    return create ? create(classId, record) : 0;
}

/* ---------------------------------------------------------------------------------------------------------- mods */

/* ---- the mods: their manifests, load order, settings and the ones switched off ----
 * A mod folder may hold mod.txt (`key: value` lines: name, version, author, description, requires, after; the last
 * two list other mods' folder names) and settings.txt (`key = value`, read through api->setting). Mods\disabled.txt
 * lists the folders the Mods menu switched off (one per line). The load order is the folders' names, except that a
 * mod loads after those it `requires` or names in `after`; a mod whose requirement is missing or switched off is not
 * loaded. Mods\cache is the loader's own folder, not a mod. */
#define MAX_KEYS 32
typedef struct {
    char folder[64];
    char name[64], version[32], author[64], description[256];
    char requires[8][64], after[8][64];
    int nrequires, nafter, disabled, placed, switchedOff; /* disabled: not loaded; switchedOff: by the Mods menu */
    char keys[MAX_KEYS][48], values[MAX_KEYS][208];
    int nkeys;
} ModInfo;
static ModInfo g_modInfo[64];
static int g_nModInfo;
static SdwModApi g_apis[64]; /* one per mod: its own mod_dir and settings */
static char g_apiDirs[64][MAX_PATH];

static char *trim(char *s)
{
    char *e;
    while (*s == ' ' || *s == '\t')
        s++;
    e = s + strlen(s);
    while (e > s && (e[-1] == ' ' || e[-1] == '\t' || e[-1] == '\r' || e[-1] == '\n'))
        *--e = 0;
    return s;
}

static int split_list(char *value, char (*out)[64], int max) /* names separated by commas or spaces */
{
    int n = 0;
    char *tok = strtok(value, ", \t");
    while (tok && n < max) {
        lstrcpynA(out[n++], tok, 64);
        tok = strtok(0, ", \t");
    }
    return n;
}

/* each line of a text file as `key<sep>value` (sep ':' or '='), `#` starting a comment, to fn */
static void read_pairs(const char *path, void (*fn)(ModInfo *, char *, char *), ModInfo *m)
{
    char *text = read_text(path), *line, *next;
    if (!text)
        return;
    for (line = text; line && *line; line = next) {
        char *sep, *hash;
        next = strchr(line, '\n');
        if (next)
            *next++ = 0;
        if ((hash = strchr(line, '#')) != 0)
            *hash = 0;
        sep = strpbrk(line, ":=");
        if (!sep)
            continue;
        *sep = 0;
        fn(m, trim(line), trim(sep + 1));
    }
    free(text);
}

static void manifest_pair(ModInfo *m, char *key, char *value)
{
    if (!_stricmp(key, "name"))
        lstrcpynA(m->name, value, sizeof m->name);
    else if (!_stricmp(key, "version"))
        lstrcpynA(m->version, value, sizeof m->version);
    else if (!_stricmp(key, "author"))
        lstrcpynA(m->author, value, sizeof m->author);
    else if (!_stricmp(key, "description"))
        lstrcpynA(m->description, value, sizeof m->description);
    else if (!_stricmp(key, "requires"))
        m->nrequires = split_list(value, m->requires, 8);
    else if (!_stricmp(key, "after"))
        m->nafter = split_list(value, m->after, 8);
}

static void settings_pair(ModInfo *m, char *key, char *value)
{
    if (m->nkeys < MAX_KEYS) {
        lstrcpynA(m->keys[m->nkeys], key, sizeof m->keys[0]);
        lstrcpynA(m->values[m->nkeys++], value, sizeof m->values[0]);
    }
}

static const char *api_setting(const SdwModApi *self, const char *key, const char *fallback)
{
    int i = (int)(self - g_apis), k;
    if (i < 0 || i >= 64)
        return fallback;
    for (k = 0; k < g_modInfo[i].nkeys; k++)
        if (!_stricmp(g_modInfo[i].keys[k], key))
            return g_modInfo[i].values[k];
    return fallback;
}

static int api_setting_int(const SdwModApi *self, const char *key, int fallback)
{
    const char *v = api_setting(self, key, 0);
    char *end;
    long n;
    if (!v)
        return fallback;
    n = strtol(v, &end, 0);
    return end != v ? (int)n : fallback;
}

static int by_folder(const void *a, const void *b)
{
    return _stricmp(((const ModInfo *)a)->folder, ((const ModInfo *)b)->folder);
}

static ModInfo *find_mod(const char *folder)
{
    int i;
    for (i = 0; i < g_nModInfo; i++)
        if (!_stricmp(g_modInfo[i].folder, folder))
            return &g_modInfo[i];
    return 0;
}

/* the installed mods, read and ordered (also for the Mods menu) */
static void scan_mods(void)
{
    char pattern[MAX_PATH], path[MAX_PATH], *text;
    WIN32_FIND_DATAA fd;
    HANDLE h;
    g_nModInfo = 0;
    _snprintf(pattern, sizeof pattern, "%sMods\\*", g_gameDir);
    if ((h = FindFirstFileA(pattern, &fd)) == INVALID_HANDLE_VALUE)
        return;
    do {
        ModInfo *m;
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) || fd.cFileName[0] == '.' ||
            !_stricmp(fd.cFileName, "cache") || g_nModInfo >= 64)
            continue;
        m = &g_modInfo[g_nModInfo++];
        memset(m, 0, sizeof *m);
        lstrcpynA(m->folder, fd.cFileName, sizeof m->folder);
        lstrcpynA(m->name, fd.cFileName, sizeof m->name);
        _snprintf(path, sizeof path, "%sMods\\%s\\mod.txt", g_gameDir, fd.cFileName);
        read_pairs(path, manifest_pair, m);
    } while (FindNextFileA(h, &fd));
    FindClose(h);
    qsort(g_modInfo, g_nModInfo, sizeof g_modInfo[0], by_folder);
    _snprintf(path, sizeof path, "%sMods\\disabled.txt", g_gameDir);
    if ((text = read_text(path)) != 0) {
        char *line, *next;
        for (line = text; line && *line; line = next) {
            ModInfo *m;
            next = strchr(line, '\n');
            if (next)
                *next++ = 0;
            if ((m = find_mod(trim(line))) != 0)
                m->disabled = m->switchedOff = 1;
        }
        free(text);
    }
}

/* the next mod to load: the first (by folder name) whose `requires` and `after` that are installed are loaded */
static ModInfo *next_in_order(void)
{
    int i, k;
    for (i = 0; i < g_nModInfo; i++) {
        ModInfo *m = &g_modInfo[i];
        int ready = !m->placed;
        for (k = 0; ready && k < m->nrequires; k++) {
            ModInfo *d = find_mod(m->requires[k]);
            ready = !d || d->placed || d->disabled;
        }
        for (k = 0; ready && k < m->nafter; k++) {
            ModInfo *d = find_mod(m->after[k]);
            ready = !d || d->placed || d->disabled;
        }
        if (ready)
            return m;
    }
    for (i = 0; i < g_nModInfo; i++) /* a cycle: the first left, as it is */
        if (!g_modInfo[i].placed) {
            log_line("%s: its requires / after go round in a circle: loaded in name order", g_modInfo[i].folder);
            return &g_modInfo[i];
        }
    return 0;
}

static void load_mods(void)
{
    char path[MAX_PATH];
    ModInfo *m;
    int loaded = 0, k;
    scan_mods();
    while ((m = next_in_order()) != 0) {
        int i = (int)(m - g_modInfo), missing = 0, r;
        char *dir = g_apiDirs[i];
        SdwModApi *api = &g_apis[i];
        HMODULE dll;
        SdwModInitFn init;
        m->placed = 1;
        lstrcpynA(g_currentMod, m->folder, sizeof g_currentMod);
        if (m->disabled) {
            log_line("switched off (Mods\\disabled.txt)");
            g_currentMod[0] = 0;
            continue;
        }
        for (k = 0; k < m->nrequires; k++) {
            ModInfo *d = find_mod(m->requires[k]);
            if (!d || d->disabled || !d->placed) {
                log_line("not loaded: it requires %s, which is %s", m->requires[k], !d ? "not installed" : "switched off");
                missing = 1;
            }
        }
        if (missing) {
            m->disabled = 1; /* so that what requires it is not loaded either */
            g_currentMod[0] = 0;
            continue;
        }
        _snprintf(dir, MAX_PATH, "%sMods\\%s\\", g_gameDir, m->folder);
        _snprintf(path, sizeof path, "%ssettings.txt", dir);
        read_pairs(path, settings_pair, m);
        _snprintf(path, sizeof path, "%s%s.dll", dir, m->folder);
        if (GetFileAttributesA(path) == INVALID_FILE_ATTRIBUTES) { /* no code: files\ and levels\ only */
            if (g_nMods < 64) {
                lstrcpynA(g_modDirs[g_nMods], dir, MAX_PATH);
                lstrcpynA(g_modNames[g_nMods], m->folder, 64);
                g_nMods++;
                loaded++;
                log_line("loaded%s%s (files and level patches only)", m->version[0] ? ", version " : "", m->version);
            }
            g_currentMod[0] = 0;
            continue;
        }
        dll = LoadLibraryA(path);
        if (!dll) {
            log_line("not loaded: %s (error %lu; a mod is Mods\\<Name>\\<Name>.dll)", path, GetLastError());
            m->disabled = 1;
            g_currentMod[0] = 0;
            continue;
        }
        init = (SdwModInitFn)GetProcAddress(dll, "SdwModInit");
        if (!init) {
            log_line("%s exports no SdwModInit; unloaded", path);
            FreeLibrary(dll);
            m->disabled = 1;
            g_currentMod[0] = 0;
            continue;
        }
        api->version = SDW_MOD_API_VERSION;
        api->game = g_gameName;
        api->mod_dir = dir;
        api->find = api_find;
        api->hook = api_hook;
        api->hook_address = api_hook_address;
        api->log = log_line;
        api->on_frame = api_on_frame;
        api->on_level_load = api_on_level_load;
        api->on_level_free = api_on_level_free;
        api->on_object_created = api_on_object_created;
        api->register_class = api_register_class;
        api->create_object = api_create_object;
        api->setting = api_setting;
        api->setting_int = api_setting_int;
        r = init(api);
        if (r == 0)
            log_line("loaded%s%s", m->version[0] ? ", version " : "", m->version);
        else
            log_line("SdwModInit returned %d: unloaded", r);
        if (r != 0) {
            FreeLibrary(dll);
            m->disabled = 1;
        } else {
            loaded++;
            if (g_nMods < 64) {
                lstrcpynA(g_modDirs[g_nMods], dir, MAX_PATH);
                lstrcpynA(g_modNames[g_nMods], m->folder, 64);
                g_nMods++;
            }
        }
        g_currentMod[0] = 0;
    }
    log_line("%d mod(s) loaded", loaded);
}

/* ---------------------------------------------------------------------------------------------------------- content */

static const char *redirect(const char *path);
static char *read_text(const char *path);

static int mods_have(const char *sub)
{
    char p[MAX_PATH];
    int i;
    for (i = 0; i < g_nMods; i++) {
        _snprintf(p, sizeof p, "%s%s", g_modDirs[i], sub);
        if (GetFileAttributesA(p) != INVALID_FILE_ATTRIBUTES)
            return 1;
    }
    return 0;
}

static char *read_text(const char *path)
{
    FILE *f = fopen(path, "rb");
    long n;
    char *s;
    if (!f)
        return 0;
    fseek(f, 0, SEEK_END);
    n = ftell(f);
    fseek(f, 0, SEEK_SET);
    s = (char *)malloc(n + 1);
    if (s) {
        n = (long)fread(s, 1, n, f);
        s[n] = 0;
    }
    fclose(f);
    return s;
}

/* Level patches: each mod's levels\\<name>.txt, in load order, applied after the game has read the level's .WAR
 * (Load_WAR) and before it creates any object. A patch that adds objects (`new`) needs room for their records inside
 * the level's image, whose offsets are 24 bits from its start: while Load_WAR runs, the malloc of the image (the one
 * of the file's size) is made larger, and the game is given a longer copy of the resource table (war.table; every
 * reader goes through that pointer and the count in the header). */
static unsigned g_warSize, g_warExtra, g_warExtraDone;
static char g_warPath[MAX_PATH];                          /* the .WAR being loaded, as the game names it */
static LevelPatchImport g_imports[LEVELPATCH_MAX_IMPORTS]; /* its imported models, built after its meshes */
static int g_nImports;
static LevelPatchImage g_images[LEVELPATCH_MAX_IMAGES]; /* the other levels' .WAR files they point into */
static int g_nImages;
static struct {
    unsigned short classId;
    char source[LEVELPATCH_PATH];
} g_brought[LEVELPATCH_MAX_IMPORTS]; /* the classes brought from other levels, for their icons and text */
static int g_nBrought;
static struct {
    unsigned short classId, length;
    char list[LEVELPATCH_TEXT];
} g_texts[16]; /* the text patches give classes */
static int g_nTexts;
static struct {
    unsigned short classId, index;
    char string[LEVELPATCH_STRING];
} g_strings[64]; /* single strings patches change or add (signs' text) */
static int g_nStrings;
static void *g_owned[64]; /* the loader's memory the level's tables point into, freed at the next load */
static int g_nOwned;
static unsigned char *import_read_war(const char *source, unsigned *size);
static int import_resolve(const char *name, char *out, unsigned n);
static const char *g_patchModDir;
static unsigned *g_newTable; /* the previous level's longer table, freed at the next load */

static void *(__cdecl *orig_malloc)(size_t n);
static void *__cdecl ev_malloc(size_t n)
{
    if (g_warExtra && n == g_warSize) {
        n += g_warExtra;
        g_warExtra = 0;
        g_warExtraDone = 1;
    }
    return orig_malloc(n);
}

static int(__cdecl *orig_Load_WAR)(const char *path, void *war);
static int __cdecl ev_Load_WAR(const char *path, void *war)
{
    char base[64], file[MAX_PATH], *texts[64], *dot;
    const char *name = strrchr(path, '\\');
    int i, r, created = 0;
    unsigned count, room = 0;
    static LevelPatchTarget target; /* large: its class and text tables */
    WIN32_FILE_ATTRIBUTE_DATA fa;
    lstrcpynA(base, name ? name + 1 : path, sizeof base);
    dot = strrchr(base, '.');
    if (dot)
        *dot = 0;
    for (i = 0; i < g_nMods; i++) {
        _snprintf(file, sizeof file, "%slevels\\%s.txt", g_modDirs[i], base);
        texts[i] = read_text(file);
        if (texts[i]) {
            created += levelpatch_count_new(texts[i]);
            room += levelpatch_room(texts[i]);
        }
    }
    g_warExtraDone = 0;
    g_nImports = 0;
    g_nBrought = g_nTexts = g_nStrings = 0;
    while (g_nOwned) /* the previous level's icon and text memory (that level has been freed) */
        free(g_owned[--g_nOwned]);
    while (g_nImages) /* the files the previous level's imported models used (that level has been freed) */
        free(g_images[--g_nImages].data);
    lstrcpynA(g_warPath, path, sizeof g_warPath);
    if (created && orig_malloc && GetFileAttributesExA(redirect(path), GetFileExInfoStandard, &fa)) {
        g_warSize = fa.nFileSizeLow;
        g_warExtra = room;
    }
    r = orig_Load_WAR(path, war);
    g_warExtra = 0;
    if (r >= 0) {
        target.blob = *(unsigned char **)((char *)war + 8); /* WarFile: header +0, table +4, blob +8 */
        target.table = *(unsigned **)((char *)war + 4);
        count = *(unsigned *)(target.blob + 0x0C);
        target.capacity = count;
        target.room_start = target.room_size = target.room_used = 0;
        target.resolve = import_resolve;
        target.load_war = import_read_war;
        target.nimports = 0;
        target.nimages = 0;
        target.nclasses = 0;
        target.ntexts = 0;
        target.nstrings = 0;
        target.nanimsFrom = 0;
        if (g_newTable) {
            free(g_newTable);
            g_newTable = 0;
        }
        if (g_warExtraDone) {
            g_newTable = (unsigned *)malloc((count + created) * sizeof(unsigned));
            if (g_newTable) {
                memcpy(g_newTable, target.table, count * sizeof(unsigned));
                target.table = g_newTable;
                *(unsigned **)((char *)war + 4) = g_newTable;
                target.capacity = count + created;
                target.room_start = (g_warSize + 3) & ~3u;
                target.room_size = room - (target.room_start - g_warSize);
            }
        }
    }
    for (i = 0; i < g_nMods; i++) {
        if (!texts[i])
            continue;
        if (r >= 0) {
            lstrcpynA(g_currentMod, g_modNames[i], sizeof g_currentMod);
            g_patchModDir = g_modDirs[i];
            log_line("%s: %d change(s) applied", base,
                     levelpatch_apply(&target, texts[i], g_sdwProps, g_sdwPropCount, log_line));
            g_patchModDir = 0;
            g_currentMod[0] = 0;
        }
        free(texts[i]);
    }
    if (r >= 0) {
        memcpy(g_imports, target.imports, target.nimports * sizeof *g_imports);
        g_nImports = target.nimports;
        memcpy(g_images, target.images, target.nimages * sizeof *g_images);
        g_nImages = target.nimages;
        memcpy(g_brought, target.classes, target.nclasses * sizeof *g_brought);
        g_nBrought = target.nclasses;
        memcpy(g_texts, target.texts, target.ntexts * sizeof *g_texts);
        g_nTexts = target.ntexts;
        memcpy(g_strings, target.strings, target.nstrings * sizeof *g_strings);
        g_nStrings = target.nstrings;
    }
    return r;
}

/* Imported models (`import` in a level patch): levelpatch.c has put each one's record into the image under a
 * placeholder type, pointing into the other level's .WAR, which stays loaded (g_images) until the next level loads.
 * Once the game has built the level's own meshes (Load_WarMeshes), the loader builds each imported one the same way,
 * with the game's code: a BsFile on the other level's .WAR, stepped to the model's frame, and a Mesh built from it, keyed in g_texObjects / g_texKeys by the record's address (as Load_WarMeshes and elastic do). The
 * BsFile reads its texture rectangles from the other level's .DAV, whose pages are not loaded here: the pages the model
 * uses are loaded as new pages of the level's PolyBatcher, inserted before its last four (blank pages the interface and
 * the map draw into, found as texturePageCount - 1 .. - 4), and the rectangles' page numbers are changed to them
 * before the Mesh is built. They draw as sorted pages (their index is past immediateTexCount). The game frees all of it
 * with the level: the pages with the PolyBatcher, the Meshes in Load_FreeWarMeshes. */
typedef void *(__cdecl *GameNewFn)(size_t);
typedef void(__cdecl *GameFreeFn)(void *);
typedef void *(__fastcall *TextureCtorFn)(void *self, void *edx, void *app, unsigned w, unsigned h, unsigned format,
                                          int *err);
typedef void(__fastcall *SurfaceLockFn)(void *self, void *edx, void *desc);
typedef void(__fastcall *SurfaceUnlockFn)(void *self);
typedef void *(__fastcall *BsFileCtorFn)(void *self, void *edx, const char *path);
typedef int(__fastcall *BsFrameFn)(void *self);
typedef void *(__fastcall *MeshCtorFn)(void *self);
typedef unsigned char(__fastcall *MeshBuildFn)(void *self, void *edx, void *app, void *bsFile);
typedef void *(__fastcall *DeletingDtorFn)(void *self, void *edx, unsigned flags);

/* PolyBatcher, BsFile, Vdx7 and Mesh fields (src/include/sdw_classes.h) */
#define PB_RENDERER 0x04
#define PB_TEXTURES 0x14
#define PB_PAGE_COUNT 0x18
#define PB_TEXTURE_DIRTY 0x24
#define PB_STATE_FLAGS 0x28
#define BS_OK 0x04
#define BS_VDX 0x20
#define VDX_RECORDS 0x0C
#define TEXTURE_SIZE 0x90
#define MESH_SIZE 0x20
#define BSFILE_SIZE 0x24
#define DDSD_SIZE 0x7C /* DDSURFACEDESC2: lPitch +0x10, lpSurface +0x24 */
#define TEX_TABLE_SIZE 512

static unsigned char *read_file(const char *path, unsigned *size)
{
    FILE *f = fopen(path, "rb");
    unsigned char *d = 0;
    long n;
    if (!f)
        return 0;
    fseek(f, 0, SEEK_END);
    n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n > 0 && (d = (unsigned char *)malloc(n)))
        *size = (unsigned)fread(d, 1, n, f);
    fclose(f);
    return d;
}

/* an import's files without the extension: <the Levels folder of the level being loaded>\\<level>\\<level>, as the
 * game names a level, or, for mod:<file>, <the patching mod's folder><file> */
static int import_resolve(const char *name, char *out, unsigned n)
{
    const char *a = strrchr(g_warPath, '\\'), *b = a;
    char *s;
    if (!strncmp(name, "mod:", 4)) {
        if (!g_patchModDir)
            return 0;
        _snprintf(out, n, "%s%s", g_patchModDir, name + 4);
        out[n - 1] = 0;
        for (s = out; *s; s++)
            if (*s == '/')
                *s = '\\';
        return 1;
    }
    while (b && b > g_warPath && b[-1] != '\\')
        b--;
    if (!a || b == g_warPath)
        return 0;
    _snprintf(out, n, "%.*s%s\\%s", (int)(b - g_warPath), g_warPath, name, name);
    out[n - 1] = 0;
    return 1;
}

static unsigned char *import_read(const char *source, const char *ext, unsigned *size, char *path, size_t n)
{
    _snprintf(path, n, "%s%s", source, ext);
    path[n - 1] = 0;
    return read_file(redirect(path), size);
}

static unsigned char *import_read_war(const char *source, unsigned *size)
{
    char path[MAX_PATH];
    return import_read(source, ".WAR", size, path, sizeof path);
}

/* a page of another level's .DAV as a new page of the PolyBatcher, before its four blank ones; its index, or -1 */
static int import_page(const LevelPatchPage *pg)
{
    GameNewFn gnew = (GameNewFn)api_find("operator_new"), gmalloc = (GameNewFn)api_find("malloc");
    GameFreeFn gdelete = (GameFreeFn)api_find("operator_delete"), gfree = (GameFreeFn)api_find("free");
    TextureCtorFn ctor = (TextureCtorFn)api_find("Texture_Ctor");
    SurfaceLockFn lock = (SurfaceLockFn)api_find("Surface_LockReadWrite");
    SurfaceUnlockFn unlock = (SurfaceUnlockFn)api_find("Surface_Unlock");
    unsigned char *pb = *(unsigned char **)api_find("g_pPolyBin"), desc[DDSD_SIZE];
    unsigned count, at, y, kind = pg->format & 0x1C, pitch;
    void **oldTex, **tex, *t;
    unsigned *oldFlags, *flags;
    unsigned char *pixels;
    int err = 0;
    if (!gnew || !gmalloc || !gdelete || !gfree || !ctor || !lock || !unlock || !pb)
        return -1;
    count = *(unsigned *)(pb + PB_PAGE_COUNT);
    if (count < 4 || !(t = gnew(TEXTURE_SIZE)))
        return -1;
    ctor(t, 0, *(void **)(pb + PB_RENDERER), pg->w, pg->h, pg->format & 3, &err);
    if (err)
        return -1; /* (the Texture's memory stays: the game's own loader gives up the same way) */
    memset(desc, 0, sizeof desc);
    *(unsigned *)desc = DDSD_SIZE;
    lock(t, 0, desc);
    pixels = *(unsigned char **)(desc + 0x24);
    pitch = *(unsigned *)(desc + 0x10) ? *(unsigned *)(desc + 0x10) : pg->w * 2;
    for (y = 0; pixels && y < pg->h; y++)
        memcpy(pixels + y * pitch, pg->pixels + y * pg->w, pg->w * 2);
    unlock(t);
    /* the arrays are the game's (freed by ~PolyBatcher with free and delete), so they are made again by its allocator */
    tex = (void **)gmalloc((count + 1) * sizeof *tex);
    flags = (unsigned *)gnew((count + 1) * sizeof *flags);
    if (!tex || !flags)
        return -1;
    oldTex = *(void ***)(pb + PB_TEXTURES);
    oldFlags = *(unsigned **)(pb + PB_STATE_FLAGS);
    at = count - 4;
    memcpy(tex, oldTex, at * sizeof *tex);
    memcpy(flags, oldFlags, at * sizeof *flags);
    tex[at] = t; /* the state flags PolyBatcher_LoadTexturePages gives a page of this kind */
    flags[at] = kind == 8 ? 0xC002 : kind == 0x10 ? 0xC004 : 0xC020;
    memcpy(tex + at + 1, oldTex + at, 4 * sizeof *tex);
    memcpy(flags + at + 1, oldFlags + at, 4 * sizeof *flags);
    *(void ***)(pb + PB_TEXTURES) = tex;
    *(unsigned **)(pb + PB_STATE_FLAGS) = flags;
    *(unsigned *)(pb + PB_PAGE_COUNT) = count + 1;
    pb[PB_TEXTURE_DIRTY] = 1; /* (a u8) the bound-page cache (lastTextureIndex) may name a page that moved */
    gfree(oldTex);
    gdelete(oldFlags);
    return (int)at;
}

/* the pages imported during this load, so two models of one level share them */
static struct {
    char source[LEVELPATCH_PATH];
    unsigned short src, dst;
} g_pageCache[128]; /* in the order the pages were added: Render_RestoreLostSurfaces reloads them in it */
static int g_nPageCache;

static int import_mesh(const LevelPatchImport *im, unsigned char *blob, unsigned *table)
{
    GameNewFn gnew = (GameNewFn)api_find("operator_new");
    BsFileCtorFn bsCtor = (BsFileCtorFn)api_find("BsFile_Ctor");
    BsFrameFn first = (BsFrameFn)api_find("BsFile_FirstFrame"), next = (BsFrameFn)api_find("BsFile_NextFrame");
    DeletingDtorFn bsDelete = (DeletingDtorFn)api_find("BsFile_ScalarDeletingDtor");
    MeshCtorFn meshCtor = (MeshCtorFn)api_find("Mesh_Construct");
    void **app = (void **)api_find("g_pD3DAppMain"), **objects = (void **)api_find("g_texObjects");
    unsigned *keys = (unsigned *)api_find("g_texKeys");
    unsigned short *texCount = (unsigned short *)api_find("g_texCount"), pages[16], newPage[16];
    char warPath[MAX_PATH], davPath[MAX_PATH];
    unsigned warSize = 0, davSize = 0, i, nrec, off = table[im->index] & 0xFFFFFF;
    unsigned char *war, *dav, *bs, *recs, *mesh;
    int np, ok = 0;
    if (!gnew || !bsCtor || !first || !next || !bsDelete || !meshCtor || !app || !objects || !keys || !texCount)
        return 0;
    if (*texCount >= TEX_TABLE_SIZE) {
        log_line("import %s %u: the level's 512 meshes are all used", im->source, im->res);
        return 0;
    }
    war = import_read(im->source, ".WAR", &warSize, warPath, sizeof warPath);
    dav = import_read(im->source, ".DAV", &davSize, davPath, sizeof davPath);
    np = war && dav ? levelpatch_model_pages(war, warSize, im->res, dav, davSize, pages, 16) : -1;
    nrec = dav ? levelpatch_dav_rects(dav, davSize) : 0;
    for (i = 0; np >= 0 && i < (unsigned)np; i++) {
        LevelPatchPage pg;
        int at = -1, c;
        for (c = 0; c < g_nPageCache; c++)
            if (g_pageCache[c].src == pages[i] && !strcmp(g_pageCache[c].source, im->source))
                at = g_pageCache[c].dst;
        if (at < 0 && levelpatch_dav_page(dav, davSize, pages[i], &pg) && (at = import_page(&pg)) >= 0 &&
            g_nPageCache < 128) {
            lstrcpynA(g_pageCache[g_nPageCache].source, im->source, sizeof g_pageCache[0].source);
            g_pageCache[g_nPageCache].src = pages[i];
            g_pageCache[g_nPageCache++].dst = (unsigned short)at;
        }
        if (at < 0) {
            np = -1;
            break;
        }
        newPage[i] = (unsigned short)at;
    }
    if (np < 0)
        log_line("import %s %u: its texture pages cannot be loaded", im->source, im->res);
    else if ((bs = (unsigned char *)gnew(BSFILE_SIZE)) != 0) {
        bsCtor(bs, 0, warPath);
        if (bs[BS_OK] == 1) {
            first(bs);
            for (i = 0; i < im->res; i++)
                next(bs);
            recs = *(unsigned char **)(*(unsigned char **)(bs + BS_VDX) + VDX_RECORDS);
            for (i = 0; i < nrec; i++) { /* {u16 x, w, y, h, page}: the model's pages become the ones loaded here */
                unsigned short *page = (unsigned short *)(recs + i * 10 + 8);
                int k;
                for (k = 0; k < np && pages[k] != *page; k++)
                    ;
                if (k < np)
                    *page = newPage[k];
            }
            if ((mesh = (unsigned char *)gnew(MESH_SIZE)) != 0) {
                meshCtor(mesh);
                ((MeshBuildFn)(*(void ***)mesh)[1])(mesh, 0, *app, bs);
                objects[*texCount] = mesh;
                keys[*texCount] = (unsigned)(size_t)(blob + off);
                (*texCount)++;
                table[im->index] = (im->type << 24) | off;
                ok = 1;
            }
        } else
            log_line("import %s %u: the game cannot open %s", im->source, im->res, warPath);
        bsDelete(bs, 0, 1);
    }
    free(war);
    free(dav);
    if (ok)
        log_line("imported %s model %u (%d texture page(s)) as resource %u", im->source, im->res, np, im->index);
    return ok;
}

/* After the game has lost its video memory (switching away from fullscreen), PolyBatcher::Render_RestoreLostSurfaces
 * deletes every texture page and loads the level's .DAV again: the pages the loader added are gone and the models and
 * pictures that use them would show the blank pages (or read past the page table). They are loaded again, in the
 * order they were first added, so each gets its number back; the game's E_FAIL for a page count that changed is then
 * answered with the count it had. */
static long(__fastcall *orig_Render_RestoreLostSurfaces)(void *self, void *edx);
static long __fastcall ev_Render_RestoreLostSurfaces(void *self, void *edx)
{
    unsigned before = *(unsigned *)((unsigned char *)self + PB_PAGE_COUNT), size = 0, c;
    long r = orig_Render_RestoreLostSurfaces(self, edx);
    unsigned char *dav = 0;
    const char *current = 0;
    char path[MAX_PATH];
    int ok = 0;
    for (c = 0; c < (unsigned)g_nPageCache; c++) {
        LevelPatchPage pg;
        int at;
        if (!current || strcmp(current, g_pageCache[c].source)) { /* read each source once (they come in runs) */
            free(dav);
            current = g_pageCache[c].source;
            dav = import_read(current, ".DAV", &size, path, sizeof path);
        }
        at = dav && levelpatch_dav_page(dav, size, g_pageCache[c].src, &pg) ? import_page(&pg) : -1;
        if (at != g_pageCache[c].dst) {
            log_line("after the lost surfaces: page %u of %s came back as %d, not %u", g_pageCache[c].src, current, at,
                     g_pageCache[c].dst);
            break;
        }
        ok++;
    }
    free(dav);
    if (g_nPageCache)
        log_line("after the lost surfaces: %d of %d added page(s) loaded again", ok, g_nPageCache);
    if (r < 0 && *(unsigned *)((unsigned char *)self + PB_PAGE_COUNT) == before)
        r = 0;
    return r;
}

static int(__cdecl *orig_Load_WarMeshes)(const char *path, void *war);
static int __cdecl ev_Load_WarMeshes(const char *path, void *war)
{
    int r = orig_Load_WarMeshes(path, war), i;
    unsigned char *blob = *(unsigned char **)((char *)war + 8);
    unsigned *table = *(unsigned **)((char *)war + 4);
    unsigned count = *(unsigned *)(blob + 0x0C), j;
    g_nPageCache = 0;
    for (i = 0; i < g_nImports; i++) {
        if (import_mesh(&g_imports[i], blob, table))
            continue;
        /* no Mesh: the objects that would show it are not created (type 1, as `remove` does), nor is the model */
        for (j = 0; j < count; j++)
            if (((table[j] >> 24) & ~0x40u) == 5 && *(unsigned short *)(blob + (table[j] & 0xFFFFFF)) == g_imports[i].index) {
                table[j] = (table[j] & 0xFFFFFF) | (1u << 24);
                log_line("resource %u not created: its model was not imported", j);
            }
        table[g_imports[i].index] = (table[g_imports[i].index] & 0xFFFFFF) | (1u << 24);
    }
    g_nImports = 0;
    return r;
}

/* File patches: files\\<path>.patch changes bytes of a game file without shipping it. Each line is an offset and the
 * bytes to write there, in hex: `0x1f24 1b 00` or `0x1f24 1b00`; `#` starts a comment. The patches of every mod apply in
 * load order, on top of the file a mod replaces if one does; the result is written once each time the game starts, to Mods\\cache\\<path>,
 * and the game opens that. A file protected by the game's CRC (its first 4 bytes are the CRC-32 of the rest, as every
 * .WAR is) gets its CRC recomputed. */
static unsigned crc32_game(const unsigned char *p, size_t n) /* the game's Crc32: no final XOR */
{
    static unsigned table[256];
    unsigned c = 0xFFFFFFFF;
    size_t i;
    if (!table[1]) {
        unsigned k, j, v;
        for (k = 0; k < 256; k++) {
            for (v = k, j = 0; j < 8; j++)
                v = v & 1 ? 0xEDB88320 ^ (v >> 1) : v >> 1;
            table[k] = v;
        }
    }
    for (i = 0; i < n; i++)
        c = table[(c ^ p[i]) & 0xFF] ^ (c >> 8);
    return c;
}

static int hexbyte(const char *s, unsigned char *out)
{
    int v = 0, i;
    for (i = 0; i < 2; i++) {
        char ch = s[i];
        v <<= 4;
        if (ch >= '0' && ch <= '9')
            v |= ch - '0';
        else if (ch >= 'a' && ch <= 'f')
            v |= ch - 'a' + 10;
        else if (ch >= 'A' && ch <= 'F')
            v |= ch - 'A' + 10;
        else
            return 0;
    }
    *out = (unsigned char)v;
    return 1;
}

static void apply_file_patch(unsigned char *data, size_t size, const char *text, const char *name)
{
    int lineNo = 0;
    const char *s = text;
    while (*s) {
        char line[1024], *p, *end;
        const char *eol = strchr(s, '\n');
        size_t len = eol ? (size_t)(eol - s) : strlen(s);
        unsigned long off;
        lineNo++;
        if (len >= sizeof line)
            len = sizeof line - 1;
        memcpy(line, s, len);
        line[len] = 0;
        s = eol ? eol + 1 : s + len;
        if ((p = strchr(line, '#')) != 0)
            *p = 0;
        p = line;
        while (*p == ' ' || *p == '\t')
            p++;
        if (!*p || *p == '\r')
            continue;
        off = strtoul(p, &end, 0);
        if (end == p) {
            log_line("%s line %d: expected an offset and bytes", name, lineNo);
            continue;
        }
        for (p = end; *p;) {
            unsigned char b;
            while (*p == ' ' || *p == '\t' || *p == '\r')
                p++;
            if (!*p)
                break;
            if (!hexbyte(p, &b)) {
                log_line("%s line %d: '%c' is not a hex byte", name, lineNo, *p);
                break;
            }
            if (off >= size) {
                log_line("%s line %d: offset 0x%lx is past the end of the file (0x%lx bytes)", name, lineNo, off,
                         (unsigned long)size);
                break;
            }
            data[off++] = b;
            p += 2;
        }
    }
}

static void make_dirs(const char *file)
{
    char d[MAX_PATH];
    char *p;
    lstrcpynA(d, file, sizeof d);
    for (p = d + 3; *p; p++)
        if (*p == '\\') {
            *p = 0;
            CreateDirectoryA(d, 0);
            *p = '\\';
        }
}

/* The game opens files on two threads (its stream loader opens music and voices with mmioOpenA), so the returned path
 * is per thread, and building a patched copy is done under a lock. */
static CRITICAL_SECTION g_contentLock;
static DWORD g_pathSlot = TLS_OUT_OF_INDEXES;
static char *thread_path(void) /* this thread's buffer for the path content_file returns */
{
    char *b;
    if (g_pathSlot == TLS_OUT_OF_INDEXES)
        g_pathSlot = TlsAlloc();
    b = (char *)TlsGetValue(g_pathSlot);
    if (!b) {
        b = (char *)malloc(MAX_PATH);
        TlsSetValue(g_pathSlot, b);
    }
    return b;
}
static const char *content_file_locked(const char *path, const char *rel);
static const char *content_file(const char *path, const char *rel)
{
    const char *r;
    EnterCriticalSection(&g_contentLock);
    r = content_file_locked(path, rel);
    LeaveCriticalSection(&g_contentLock);
    return r;
}

/* Sounds: a mod's sounds\\<Level>\\<id>.wav (or sounds\\<id>.wav, for every level) are added to the level's sound bank,
 * the .SND the game loads with it (Load_SND): {u32; "vdx7"; u16 count; u16; then per sound {u32 id; u32 size; u32 loop;
 * a RIFF/WAVE image of that size}}, at most 256 (g_sndBankEntries). Sound_Play finds a sound by its id, the first in
 * the bank: a mod sound with a game sound's id replaces it (the game's entry gets id 0xFFFFFFFF). <id> is decimal or
 * 0x hex, up to 0xFFFF (Sound_Play's is a u16; the game's own go up to 0x157, and a bank holds at most 84 of them).
 * Like a file patch, the result is a copy in Mods\\cache. */
#define SND_MAX 256

static int sound_dir(int mod, const char *rel, int all, char *out, size_t n) /* its sounds folder for this .SND */
{
    const char *file = strrchr(rel, '\\'), *dot = strrchr(rel, '.');
    if (!file || !dot || _stricmp(dot, ".SND") || _strnicmp(rel, "Levels\\", 7))
        return 0;
    if (all)
        _snprintf(out, n, "%ssounds\\", g_modDirs[mod]);
    else
        _snprintf(out, n, "%ssounds\\%.*s\\", g_modDirs[mod], (int)(dot - file - 1), file + 1);
    out[n - 1] = 0;
    return 1;
}

/* a mod's level patch for the level of this .SND (levels\<Level>.txt), for its `sound <id> from <Level>` lines */
static char *sound_patch(int mod, const char *rel)
{
    const char *file = strrchr(rel, '\\'), *dot = strrchr(rel, '.');
    char path[MAX_PATH];
    if (!file || !dot || dot < file)
        return 0;
    _snprintf(path, sizeof path, "%slevels\\%.*s.txt", g_modDirs[mod], (int)(dot - file - 1), file + 1);
    path[sizeof path - 1] = 0;
    return read_text(path);
}

/* the next `sound <id> from <Level>` line of a patch text from *s on: 1 with the id and the level, 0 at the end */
static int next_sound_line(const char **s, unsigned long *id, char *level, size_t n)
{
    while (**s) {
        const char *line = *s, *eol = strchr(line, '\n');
        char from[8], *stop;
        int got;
        *s = eol ? eol + 1 : line + strlen(line);
        while (*line == ' ' || *line == '\t')
            line++;
        if (strncmp(line, "sound", 5) || (line[5] != ' ' && line[5] != '\t'))
            continue;
        level[0] = 0;
        got = sscanf(line + 5, "%lu%*[ \t]%7s%*[ \t]%63[A-Za-z0-9_-]", id, from, level);
        if (got < 3 || strcmp(from, "from")) { /* also 0x hex */
            *id = strtoul(line + 5, &stop, 0);
            got = sscanf(stop, "%*[ \t]%7s%*[ \t]%63[A-Za-z0-9_-]", from, level) + 1;
        }
        if (got == 3 && !strcmp(from, "from") && level[0] && strlen(level) < n)
            return 1;
        log_line("expected sound <id> from <Level>: %.*s", (int)(eol ? eol - line : (int)strlen(line)), line);
    }
    return 0;
}

/* the next `new <name> from <Level> <res>` line of a patch text whose <Level> is a level (not mod:) */
static int next_new_line(const char **s, char *level, size_t n, unsigned long *res)
{
    while (**s) {
        const char *line = *s, *eol = strchr(line, '\n');
        char name[32], from[8], lv[64], r[16], *stop;
        *s = eol ? eol + 1 : line + strlen(line);
        while (*line == ' ' || *line == '\t')
            line++;
        if (strncmp(line, "new", 3) || (line[3] != ' ' && line[3] != '\t'))
            continue;
        if (sscanf(line + 3, "%31s %7s %63s %15s", name, from, lv, r) == 4 && !strcmp(from, "from") && r[0] != '#' &&
            strncmp(lv, "mod:", 4) && strlen(lv) < n && strspn(lv, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_") == strlen(lv)) {
            *res = strtoul(r, &stop, 0);
            if (!*stop) {
                strcpy(level, lv);
                return 1;
            }
        }
    }
    return 0;
}

static int count_sounds(const char *rel)
{
    char dir[MAX_PATH], pat[MAX_PATH], level[64];
    WIN32_FIND_DATAA fd;
    HANDLE h;
    int i, all, n = 0;
    for (i = 0; i < g_nMods; i++) {
        char *text = sound_patch(i, rel);
        for (all = 0; all < 2; all++) {
            if (!sound_dir(i, rel, all, dir, sizeof dir)) {
                free(text);
                return 0;
            }
            _snprintf(pat, sizeof pat, "%s*.wav", dir);
            if ((h = FindFirstFileA(pat, &fd)) == INVALID_HANDLE_VALUE)
                continue;
            do
                n++;
            while (FindNextFileA(h, &fd));
            FindClose(h);
        }
        if (text) {
            const char *s = text;
            unsigned long id;
            while (next_sound_line(&s, &id, level, sizeof level))
                n++;
            for (s = text; next_new_line(&s, level, sizeof level, &id);)
                n++;
            free(text);
        }
    }
    return n;
}

/* one sound at the end of a .SND image's entries (anything after them stays last); with `replace`, a sound of the
 * same id already there is disabled (id 0xFFFFFFFF), otherwise the new one is not added. 1 if added. */
static int bank_append(unsigned char **pdata, long *pn, unsigned *pend, unsigned *pcount, unsigned long id,
                       const unsigned char *wav, unsigned size, unsigned loop, int replace, const char *rel)
{
    unsigned char *data = *pdata, *grown;
    unsigned e, o;
    if (*pcount >= SND_MAX) {
        log_line("%s: the bank is full (%d sounds): sound %lu not added", rel, SND_MAX, id);
        return 0;
    }
    for (e = 12, o = 0; o < *pcount; o++, e += 12 + *(unsigned *)(data + e + 4))
        if (*(unsigned *)(data + e) == id) {
            if (replace <= 0) { /* -1: quietly */
                if (!replace)
                    log_line("%s: sound %lu is in the bank already", rel, id);
                return 0;
            }
            *(unsigned *)(data + e) = 0xFFFFFFFF; /* replaced */
            log_line("%s: sound %lu replaced", rel, id);
        }
    if (!(grown = (unsigned char *)realloc(data, *pn + 12 + size)))
        return 0;
    data = grown;
    memmove(data + *pend + 12 + size, data + *pend, *pn - *pend);
    ((unsigned *)(data + *pend))[0] = id;
    ((unsigned *)(data + *pend))[1] = size;
    ((unsigned *)(data + *pend))[2] = loop;
    memcpy(data + *pend + 12, wav, size);
    *pend += 12 + size;
    *pn += 12 + size;
    *(unsigned short *)(data + 8) = (unsigned short)++*pcount;
    *pdata = data;
    return 1;
}

/* appends the mods' sounds to a .SND image (realloc'd): their sounds\ files, then the sounds their level patch takes
 * from other levels' banks (the game's own files, read here: `sound <id> from <Level>`). The number added. */
static int add_sounds(unsigned char **pdata, long *pn, const char *rel)
{
    unsigned count, i, end;
    int mod, all, added = 0;
    if (*pn < 12 || memcmp(*pdata + 4, "vdx7", 4))
        return 0;
    count = *(unsigned short *)(*pdata + 8);
    for (end = 12, i = 0; i < count && end + 12 <= (unsigned)*pn; i++) /* the entries end where the last sound does */
        end += 12 + *(unsigned *)(*pdata + end + 4);
    if (i < count || end > (unsigned)*pn)
        return 0;
    for (mod = 0; mod < g_nMods; mod++) {
        char *text;
        lstrcpynA(g_currentMod, g_modNames[mod], sizeof g_currentMod);
        for (all = 1; all >= 0; all--) { /* the sounds for every level, then this level's */
            char dir[MAX_PATH], pat[MAX_PATH], file[MAX_PATH], *stop;
            WIN32_FIND_DATAA fd;
            HANDLE h;
            sound_dir(mod, rel, all, dir, sizeof dir);
            _snprintf(pat, sizeof pat, "%s*.wav", dir);
            if ((h = FindFirstFileA(pat, &fd)) == INVALID_HANDLE_VALUE)
                continue;
            do {
                unsigned long id = strtoul(fd.cFileName, &stop, 0);
                unsigned size = 0;
                unsigned char *wav = 0;
                _snprintf(file, sizeof file, "%s%s", dir, fd.cFileName);
                if (_stricmp(stop, ".wav") || id > 0xFFFF) /* Sound_Play takes a u16 id */
                    log_line("%s: %s is not named <id>.wav with an id up to 0xFFFF", rel, file);
                else if (!(wav = read_file(file, &size)) || size < 12 || memcmp(wav, "RIFF", 4))
                    log_line("%s: %s is not a .wav", rel, file);
                else if (bank_append(pdata, pn, &end, &count, id, wav, size, 0, 1, rel)) {
                    added++;
                    log_line("%s: sound %lu added (%s)", rel, id, fd.cFileName);
                }
                free(wav);
            } while (FindNextFileA(h, &fd));
            FindClose(h);
        }
        if ((text = sound_patch(mod, rel)) != 0) {
            const char *s = text;
            char level[64], path[MAX_PATH];
            unsigned long id;
            while (next_sound_line(&s, &id, level, sizeof level)) {
                unsigned size = 0, e, o, n;
                unsigned char *bank;
                int found = 0;
                _snprintf(path, sizeof path, "%sLevels\\%s\\%s.SND", g_gameDir, level, level);
                path[sizeof path - 1] = 0;
                bank = read_file(path, &size);
                n = bank && size >= 12 && !memcmp(bank + 4, "vdx7", 4) ? *(unsigned short *)(bank + 8) : 0;
                for (e = 12, o = 0; o < n && e + 12 <= size; o++, e += 12 + *(unsigned *)(bank + e + 4))
                    if (*(unsigned *)(bank + e) == id && *(unsigned *)(bank + e + 4) <= size - e - 12) {
                        found = 1;
                        if (bank_append(pdata, pn, &end, &count, id, bank + e + 12, *(unsigned *)(bank + e + 4),
                                        *(unsigned *)(bank + e + 8), 0, rel)) {
                            added++;
                            log_line("%s: sound %lu added from %s", rel, id, level);
                        }
                        break;
                    }
                if (!found)
                    log_line("%s: %s has no sound %lu", rel, bank ? level : path, id);
                free(bank);
            }
            for (s = text; next_new_line(&s, level, sizeof level, &id);) { /* an object's sounds come with it */
                char warPath[MAX_PATH], mine[MAX_PATH];
                unsigned short ids[64];
                unsigned srcSize = 0, dstSize = 0, bankSize = 0, e, o, nb, got = 0;
                unsigned char *srcWar, *dstWar, *bank;
                int nids, k;
                const char *dot = strrchr(rel, '.');
                _snprintf(warPath, sizeof warPath, "%sLevels\\%s\\%s.WAR", g_gameDir, level, level);
                _snprintf(mine, sizeof mine, "%s%.*s.WAR", g_gameDir, (int)(dot ? dot - rel : (int)strlen(rel)), rel);
                _snprintf(path, sizeof path, "%sLevels\\%s\\%s.SND", g_gameDir, level, level);
                srcWar = read_file(warPath, &srcSize);
                dstWar = read_file(mine, &dstSize);
                bank = read_file(path, &bankSize);
                nids = srcWar && dstWar ? levelpatch_object_sounds(srcWar, srcSize, dstWar, dstSize, (unsigned)id,
                                                                   g_sdwClassSounds, g_sdwClassSoundCount, ids, 64) : -1;
                nb = bank && bankSize >= 12 && !memcmp(bank + 4, "vdx7", 4) ? *(unsigned short *)(bank + 8) : 0;
                for (k = 0; k < nids; k++) {
                    for (e = 12, o = 0; o < nb && e + 12 <= bankSize; o++, e += 12 + *(unsigned *)(bank + e + 4))
                        if (*(unsigned *)(bank + e) == ids[k] && *(unsigned *)(bank + e + 4) <= bankSize - e - 12) {
                            if (bank_append(pdata, pn, &end, &count, ids[k], bank + e + 12, *(unsigned *)(bank + e + 4),
                                            *(unsigned *)(bank + e + 8), -1, rel)) {
                                added++;
                                got++;
                            }
                            break;
                        }
                }
                if (nids < 0)
                    log_line("%s: the sounds of %s's object %lu cannot be worked out", rel, level, id);
                else
                    log_line("%s: %s's object %lu: %u of its %d sound(s) added (the others are here already)", rel,
                             level, id, got, nids);
                free(srcWar);
                free(dstWar);
                free(bank);
            }
            free(text);
        }
        g_currentMod[0] = 0;
    }
    return added;
}

/* a conflict report, once per file: two mods replace the same game file */
static void file_conflict(const char *rel, const char *earlier, const char *later)
{
    static char reported[32][MAX_PATH];
    static int n;
    int i;
    for (i = 0; i < n; i++)
        if (!_stricmp(reported[i], rel))
            return;
    if (n < 32)
        lstrcpynA(reported[n++], rel, MAX_PATH);
    log_line("conflict: %s is replaced by two mods: %s's is used, not %s", rel, later, earlier);
}

static const char *content_file_locked(const char *path, const char *rel)
{
    char *out = thread_path();
    static char built[64][MAX_PATH]; /* patched copies already written since the game started */
    static int nbuilt;
    char full[MAX_PATH], base[MAX_PATH];
    int i, patches = 0;
    lstrcpynA(base, path, sizeof base);
    for (i = 0; i < g_nMods; i++) {
        _snprintf(full, sizeof full, "%sfiles\\%s", g_modDirs[i], rel);
        if (GetFileAttributesA(full) != INVALID_FILE_ATTRIBUTES) {
            if (strcmp(base, path)) /* another mod replaces it too: the later one wins */
                file_conflict(rel, base, g_modNames[i]);
            lstrcpynA(base, full, sizeof base); /* the last mod that replaces it */
        }
        _snprintf(full, sizeof full, "%sfiles\\%s.patch", g_modDirs[i], rel);
        patches += GetFileAttributesA(full) != INVALID_FILE_ATTRIBUTES;
    }
    patches += count_sounds(rel);
    if (!patches) {
        if (strcmp(base, path)) {
            lstrcpynA(out, base, MAX_PATH);
            log_line("%s -> %s", path, out);
            return out;
        }
        return path;
    }
    _snprintf(out, MAX_PATH, "%sMods\\cache\\%s", g_gameDir, rel);
    for (i = 0; i < nbuilt; i++)
        if (!_stricmp(built[i], out))
            return out;
    {
        FILE *f = fopen(base, "rb");
        unsigned char *data;
        long n;
        int crc;
        if (!f) {
            log_line("%s: cannot read %s to patch it", rel, base);
            return path;
        }
        fseek(f, 0, SEEK_END);
        n = ftell(f);
        fseek(f, 0, SEEK_SET);
        data = (unsigned char *)malloc(n ? n : 1);
        if (!data || fread(data, 1, n, f) != (size_t)n) {
            fclose(f);
            free(data);
            return path;
        }
        fclose(f);
        crc = n >= 4 && *(unsigned *)data == crc32_game(data + 4, n - 4);
        for (i = 0; i < g_nMods; i++) {
            char *text;
            _snprintf(full, sizeof full, "%sfiles\\%s.patch", g_modDirs[i], rel);
            text = read_text(full);
            if (!text)
                continue;
            lstrcpynA(g_currentMod, g_modNames[i], sizeof g_currentMod);
            apply_file_patch(data, (size_t)n, text, rel);
            g_currentMod[0] = 0;
            free(text);
        }
        add_sounds(&data, &n, rel);
        if (crc)
            *(unsigned *)data = crc32_game(data + 4, n - 4);
        make_dirs(out);
        f = fopen(out, "wb");
        if (!f || fwrite(data, 1, n, f) != (size_t)n) {
            if (f)
                fclose(f);
            free(data);
            log_line("%s: cannot write %s", rel, out);
            return path;
        }
        fclose(f);
        free(data);
        if (nbuilt < 64)
            lstrcpynA(built[nbuilt++], out, MAX_PATH);
        log_line("%s -> %s (%d patch file(s) or sound(s)%s)", path, out, patches, crc ? ", CRC recomputed" : "");
    }
    return out;
}

/* File overrides: a file the game opens is taken from the last loaded mod that has it under files\, at the same path
 * relative to the game's folder (files\Levels\Lvl-03\Lvl-03.DAV replaces Levels\Lvl-03\Lvl-03.DAV). */
static const char *redirect(const char *path)
{
    char rel[MAX_PATH];
    const char *r = path;
    size_t n = strlen(g_gameDir);
    int i;
    static const char *content[] = {"Levels", "Musics", "Voices", "References", "Bonus"};
    int k;
    if (!path)
        return path;
    if (!_strnicmp(path, g_gameDir, n))
        r = path + n;
    while (r[0] == '.' && (r[1] == '\\' || r[1] == '/'))
        r += 2;
    if (r[0] && r[1] == ':') { /* the game builds its folder from its command line, which need not be spelled as
                                  GetModuleFileName spells it: find one of its content folders instead */
        for (k = 0; k < (int)(sizeof content / sizeof *content); k++) {
            const char *s;
            size_t m = strlen(content[k]);
            for (s = path; *s; s++)
                if ((*s == '\\' || *s == '/') && !_strnicmp(s + 1, content[k], m) &&
                    (s[m + 1] == '\\' || s[m + 1] == '/'))
                    break;
            if (*s) {
                r = s + 1;
                break;
            }
        }
        if (r[0] && r[1] == ':')
            return path; /* elsewhere on disk */
    }
    lstrcpynA(rel, r, sizeof rel);
    for (i = 0; rel[i]; i++) /* "a\.\b" -> "a\b" */
        if ((rel[i] == '\\' || rel[i] == '/') && rel[i + 1] == '.' && (rel[i + 2] == '\\' || rel[i + 2] == '/'))
            memmove(rel + i, rel + i + 2, strlen(rel + i + 2) + 1);
    return content_file(path, rel);
}

/* Icons and text for the classes brought from other levels, once the game has registered its classes (the
 * registry's icons are the first entry of the class's icon id lists in this level's .DAV, 0 when it has none):
 * - an icon this level lacks is looked up in the other level's .DAV (id list -> index -> {x, w, y, h, page}), its
 *   page loaded as a new PolyBatcher page (import_page), its rectangle appended to this level's bitmap table (a
 *   longer copy, the loader's) and the registry pointed at a cell holding its index (UiIcon_Setup reads
 *   bitmaps[*icon]);
 * - a class's list of the text bank (.MLT, list class + 1: its name and help, Text_GetClassString) is taken from the
 *   other level's bank, in the language the game loaded (found by matching list 0), when this level's is empty; a
 *   `text` line of a patch sets it outright. */
static void *owned(size_t n)
{
    void *p = g_nOwned < 64 ? malloc(n) : 0;
    if (p)
        g_owned[g_nOwned++] = p;
    return p;
}

/* ---- pictures brought from other levels ----
 * A level's pictures are its .DAV's id lists ({u16 id; u16 n; u32 entry[n]}, g_idListBlob / g_idListCount, relocated
 * by Load_DAV): an entry is the address of a u16 in the index table (whose value is a bitmap record's number: what an
 * icon or a Sprite reads) or of a bitmap record itself (a sprite's frames: Res_FindBitmapGroup matches a record's
 * ADDRESS against them). A picture this level lacks is brought in one pass: its records' texture pages are loaded as
 * new PolyBatcher pages, the bitmap table, the index table and the list blob are replaced by longer copies (the
 * loader's), and every existing entry that pointed into the old tables is moved with them (Res_GetValidatedIdList
 * checks an entry against the index table's bounds, AnimSprite::InitFromRes finds the crayon frame by address). */
#define MAX_PICS 32
typedef struct {
    unsigned short id;
    char source[LEVELPATCH_PATH];
    ClassEntry *icon; /* a registry icon to point at it (iconA / iconB by `which`), or 0 */
    int which;
} PicWant;

static int isRecordList(const unsigned *list, unsigned bm, unsigned nb) /* its first entry is a record's address */
{
    return list[1] >= bm && list[1] < bm + 10 * nb;
}

static const unsigned *id_list_find(const unsigned *p, unsigned count, unsigned short id)
{
    unsigned i;
    for (i = 0; p && i < count; i++) {
        if ((*p & 0xFFFF) == id)
            return p;
        p += (*p >> 16) + 1;
    }
    return 0;
}

static int bring_pictures(PicWant *want, int nwant)
{
    unsigned char *hd = *(unsigned char **)api_find("g_pDav"), *dir, *davOf[MAX_PICS];
    unsigned **blobp = (unsigned **)api_find("g_idListBlob"), *countp = (unsigned *)api_find("g_idListCount");
    unsigned sizeOf[MAX_PICS], oldWords = 0, i, k, w, nrec = 0, nidx = 0, nlistWords = 0, bitmapCount, indexCount;
    unsigned char *oldBitmaps, *oldIndices, *bitmaps, *indices;
    unsigned *blob, *out;
    struct {
        const char *source;
        unsigned short srcBitmap, newBitmap;
    } recs[MAX_PICS * 4];
    struct {
        const unsigned char *dav;
        unsigned size;
        const unsigned *list; /* in the source file: its header then its entries (file offsets) */
        unsigned ind, bm, nb;
    } got[MAX_PICS];
    int n = 0, brought = 0;
    if (!hd || !blobp || !countp || !nwant)
        return 0;
    dir = *(unsigned char **)(*(unsigned char **)hd + 0x14); /* Dav.header->dir */
    indexCount = *(unsigned short *)dir;
    bitmapCount = *(unsigned short *)(dir + 2);
    oldIndices = *(unsigned char **)(dir + 6);
    oldBitmaps = *(unsigned char **)(dir + 0xa);
    for (i = 0; i < (unsigned)nwant && i < MAX_PICS; i++) { /* each wanted list, from its level's .DAV */
        char path[MAX_PATH];
        unsigned h, idl, cnt, o, e;
        got[i].list = 0;
        davOf[i] = 0;
        for (k = 0; k < i; k++) /* the same source read once */
            if (!strcmp(want[k].source, want[i].source) && davOf[k]) {
                got[i].dav = davOf[k];
                got[i].size = sizeOf[k];
                break;
            }
        if (k == i) {
            davOf[i] = import_read(want[i].source, ".DAV", &sizeOf[i], path, sizeof path);
            got[i].dav = davOf[i];
            got[i].size = sizeOf[i];
        }
        if (!got[i].dav || got[i].size < 0x18 || (h = *(unsigned *)(got[i].dav + 0x14)) + 0x16 > got[i].size)
            continue;
        got[i].ind = *(unsigned *)(got[i].dav + h + 6);
        got[i].bm = *(unsigned *)(got[i].dav + h + 0xa);
        got[i].nb = *(unsigned short *)(got[i].dav + h + 2);
        idl = *(unsigned *)(got[i].dav + h + 0x12);
        cnt = idl + 4 <= got[i].size ? *(unsigned *)(got[i].dav + idl) : 0;
        for (o = idl + 4, k = 0; k < cnt && o + 4 <= got[i].size; k++) {
            unsigned hdr = *(unsigned *)(got[i].dav + o), m = hdr >> 16;
            if (o + 4 + 4 * m > got[i].size)
                break;
            if ((hdr & 0xFFFF) == want[i].id && m) {
                got[i].list = (const unsigned *)(got[i].dav + o);
                break;
            }
            o += 4 + 4 * m;
        }
        for (k = 0; got[i].list && k < (got[i].list[0] >> 16); k++) { /* its records: numbers in its level */
            unsigned bi, r;
            e = got[i].list[1 + k];
            if (e >= got[i].bm && e < got[i].bm + 10 * got[i].nb)
                bi = (e - got[i].bm) / 10; /* a record's address */
            else if (e >= got[i].ind && e + 2 <= got[i].size)
                bi = *(unsigned short *)(got[i].dav + e), nidx++; /* an index */
            else {
                got[i].list = 0;
                break;
            }
            if (bi >= got[i].nb || got[i].bm + 10 * bi + 10 > got[i].size) {
                got[i].list = 0;
                break;
            }
            for (r = 0; r < (unsigned)n && !(recs[r].srcBitmap == bi && recs[r].source == want[i].source); r++)
                ;
            if (r == (unsigned)n && n < MAX_PICS * 4) {
                recs[n].source = want[i].source;
                recs[n].srcBitmap = (unsigned short)bi;
                recs[n++].newBitmap = (unsigned short)(bitmapCount + nrec++);
            }
        }
        if (got[i].list)
            nlistWords += 1 + (got[i].list[0] >> 16);
        else
            log_line("picture %u: not in %s", want[i].id, want[i].source);
    }
    if (!nlistWords) {
        for (i = 0; i < (unsigned)nwant && i < MAX_PICS; i++)
            free(davOf[i]);
        return 0;
    }
    for (w = 0, i = 0; i < *countp; i++) /* the old blob's length in words */
        w += 1 + ((*blobp)[w] >> 16);
    oldWords = w;
    bitmaps = (unsigned char *)owned((bitmapCount + nrec) * 10u);
    indices = (unsigned char *)owned((indexCount + nidx) * 2u + 2);
    blob = (unsigned *)owned((oldWords + nlistWords) * 4u);
    if (!bitmaps || !indices || !blob)
        goto done;
    memcpy(bitmaps, oldBitmaps, bitmapCount * 10u);
    memcpy(indices, oldIndices, indexCount * 2u);
    memcpy(blob, *blobp, oldWords * 4u);
    for (w = 0, i = 0; i < *countp; i++) { /* the entries into the old tables follow them */
        unsigned m = blob[w] >> 16;
        for (k = 1; k <= m; k++) {
            unsigned e = blob[w + k];
            if (e >= (unsigned)(size_t)oldBitmaps && e < (unsigned)(size_t)oldBitmaps + bitmapCount * 10u)
                blob[w + k] = e - (unsigned)(size_t)oldBitmaps + (unsigned)(size_t)bitmaps;
            else if (e >= (unsigned)(size_t)oldIndices && e < (unsigned)(size_t)oldIndices + indexCount * 2u)
                blob[w + k] = e - (unsigned)(size_t)oldIndices + (unsigned)(size_t)indices;
        }
        w += m + 1;
    }
    for (k = 0; k < (unsigned)n; k++) { /* the new records, their pages loaded here */
        unsigned short rec[5];
        int page = -1, c, src;
        LevelPatchPage pg;
        for (src = 0; src < nwant && want[src].source != recs[k].source; src++)
            ;
        memcpy(rec, got[src].dav + got[src].bm + 10u * recs[k].srcBitmap, 10);
        for (c = 0; c < g_nPageCache; c++)
            if (g_pageCache[c].src == rec[4] && !strcmp(g_pageCache[c].source, recs[k].source))
                page = g_pageCache[c].dst;
        if (page < 0 && levelpatch_dav_page(got[src].dav, got[src].size, rec[4], &pg) && (page = import_page(&pg)) >= 0 &&
            g_nPageCache < 128) {
            lstrcpynA(g_pageCache[g_nPageCache].source, recs[k].source, sizeof g_pageCache[0].source);
            g_pageCache[g_nPageCache].src = rec[4];
            g_pageCache[g_nPageCache++].dst = (unsigned short)page;
        }
        rec[4] = (unsigned short)(page < 0 ? 0 : page);
        memcpy(bitmaps + 10u * recs[k].newBitmap, rec, 10);
    }
    out = blob + oldWords;
    nidx = 0;
    for (i = 0; i < (unsigned)nwant && i < MAX_PICS; i++) { /* the new lists */
        unsigned m;
        if (!got[i].list)
            continue;
        m = got[i].list[0] >> 16;
        *out++ = got[i].list[0];
        for (k = 0; k < m; k++) {
            unsigned e = got[i].list[1 + k], bi, r;
            int isRecord = e >= got[i].bm && e < got[i].bm + 10 * got[i].nb;
            bi = isRecord ? (e - got[i].bm) / 10 : *(unsigned short *)(got[i].dav + e);
            for (r = 0; r < (unsigned)n && !(recs[r].srcBitmap == bi && recs[r].source == want[i].source); r++)
                ;
            if (isRecord)
                *out++ = (unsigned)(size_t)(bitmaps + 10u * recs[r].newBitmap);
            else {
                ((unsigned short *)indices)[indexCount + nidx] = recs[r].newBitmap;
                *out++ = (unsigned)(size_t)(indices + 2u * (indexCount + nidx++));
            }
        }
        if (want[i].icon && !isRecordList(got[i].list, got[i].bm, got[i].nb)) {
            unsigned short *slot = (unsigned short *)(size_t)out[-(int)m];
            if (want[i].which)
                want[i].icon->iconB = slot;
            else
                want[i].icon->iconA = slot;
        }
        brought++;
        log_line("picture %u from %s (%u record(s))", want[i].id, want[i].source, m);
    }
    *(unsigned char **)(dir + 6) = indices;
    *(unsigned char **)(dir + 0xa) = bitmaps;
    *(unsigned short *)dir = (unsigned short)(indexCount + nidx);
    *(unsigned short *)(dir + 2) = (unsigned short)(bitmapCount + nrec);
    *blobp = blob;
    *countp += (unsigned)brought;
done:
    for (i = 0; i < (unsigned)nwant && i < MAX_PICS; i++)
        free(davOf[i]);
    return brought;
}

static void set_text(unsigned short cls, const unsigned char *list, unsigned length, const char *what)
{
    unsigned char *dav = *(unsigned char **)api_find("g_pDav");
    unsigned short *countp = (unsigned short *)(dav + 0x14);
    char ***lists = (char ***)(dav + 0x18), *copy;
    GameNewFn gmalloc = (GameNewFn)api_find("malloc");
    GameFreeFn gfree = (GameFreeFn)api_find("free");
    static char empty[1];
    if (!*lists || !gmalloc || !gfree || !(copy = (char *)owned(length)))
        return;
    if (*countp <= cls + 1u) { /* a longer table, the game's (Load_FreeMLT frees it) */
        char **grown = (char **)gmalloc((cls + 2u) * sizeof *grown);
        unsigned i;
        if (!grown)
            return;
        for (i = 0; i < cls + 2u; i++)
            grown[i] = i < *countp ? (*lists)[i] : empty;
        gfree(*lists);
        *lists = grown;
        *countp = cls + 2;
    }
    memcpy(copy, list, length);
    (*lists)[cls + 1] = copy;
    log_line("class %u: its text (%u string(s)) from %s", cls, (unsigned)(unsigned char)list[0], what);
}

static void bring_icons_and_text(ClassEntry *reg)
{
    unsigned char *dav = *(unsigned char **)api_find("g_pDav"), *mine = 0;
    char path[MAX_PATH], mlt[MAX_PATH];
    unsigned mineSize = 0, len;
    int i, k, block = -1;
    if (!dav)
        return;
    {
        static PicWant want[MAX_PICS];
        const unsigned *blob = *(const unsigned **)api_find("g_idListBlob");
        unsigned count = *(const unsigned *)api_find("g_idListCount");
        int nwant = 0, j, q;
        for (i = 0; i < g_nBrought; i++) { /* the pictures its class needs that this level lacks */
            unsigned short c = g_brought[i].classId, ids[40];
            int nids = 0, which[40];
            ClassEntry *icon[40];
            if (c >= 200)
                continue;
            for (j = 0; j < 2; j++)
                if (!(j ? reg[c].iconB : reg[c].iconA) && g_iconIds[c][j]) {
                    ids[nids] = g_iconIds[c][j];
                    icon[nids] = &reg[c];
                    which[nids++] = j;
                }
            for (j = 0; j < g_sdwClassPictureCount && nids < 40; j++)
                if (g_sdwClassPictures[j][0] == c && !id_list_find(blob, count, g_sdwClassPictures[j][1])) {
                    ids[nids] = g_sdwClassPictures[j][1];
                    icon[nids] = 0;
                    which[nids++] = 0;
                }
            for (j = 0; j < nids && nwant < MAX_PICS; j++) {
                for (q = 0; q < nwant && want[q].id != ids[j]; q++)
                    ;
                if (q < nwant) { /* wanted already (an icon id also named by the code) */
                    if (icon[j]) {
                        want[q].icon = icon[j];
                        want[q].which = which[j];
                    }
                    continue;
                }
                want[nwant].id = ids[j];
                lstrcpynA(want[nwant].source, g_brought[i].source, sizeof want[0].source);
                want[nwant].icon = icon[j];
                want[nwant++].which = which[j];
            }
        }
        if (nwant)
            log_line("%d picture(s) brought from other levels", bring_pictures(want, nwant));
    }
    for (i = 0; i < g_nBrought; i++) { /* text: from the other level, in the loaded language */
        unsigned short c = g_brought[i].classId, count = *(unsigned short *)(dav + 0x14);
        char **lists = *(char ***)(dav + 0x18);
        unsigned char *theirs;
        unsigned size = 0;
        const unsigned char *l;
        for (k = 0; k < g_nTexts && g_texts[k].classId != c; k++)
            ;
        if (k < g_nTexts || !lists || (c + 1u < count && lists[c + 1][0]))
            continue; /* a patch gives it text, or this level has some */
        if (block < 0) {
            lstrcpynA(mlt, g_warPath, sizeof mlt);
            if (strlen(mlt) > 4)
                strcpy(mlt + strlen(mlt) - 4, ".MLT");
            if (!mine)
                mine = read_file(redirect(mlt), &mineSize);
            l = mine ? levelpatch_mlt_list(mine, mineSize, 0, 0, &len) : 0;
            block = l ? levelpatch_mlt_block(mine, mineSize, 0, (const unsigned char *)lists[0]) : -1;
            if (block < 0) {
                log_line("the loaded text's language is not found in %s: no text brought", mlt);
                break;
            }
        }
        if ((theirs = import_read(g_brought[i].source, ".MLT", &size, path, sizeof path)) != 0 &&
            (l = levelpatch_mlt_list(theirs, size, (unsigned)block, c + 1u, &len)) != 0 && l[0])
            set_text(c, l, len, path);
        free(theirs);
    }
    free(mine);
    for (k = 0; k < g_nTexts; k++)
        if (g_texts[k].classId < 0xFFFF)
            set_text(g_texts[k].classId, (const unsigned char *)g_texts[k].list, g_texts[k].length, "a patch");
    for (k = 0; k < g_nStrings; k++) { /* single strings, over the list the class has now (in the loaded language) */
        unsigned short c = g_strings[k].classId, count = *(unsigned short *)(dav + 0x14);
        char **lists = *(char ***)(dav + 0x18);
        const char *have[256], *cur;
        unsigned n = 0, j, size = 1, idx = g_strings[k].index;
        unsigned char *list, *o;
        if (lists && c + 1u < count && (cur = lists[c + 1]) != 0) {
            n = (unsigned char)*cur++;
            for (j = 0; j < n; j++, cur += strlen(cur) + 1)
                have[j] = cur;
        }
        for (j = n; j <= idx; j++) /* past its last: the strings between are empty */
            have[j] = "";
        if (idx >= n)
            n = idx + 1;
        have[idx] = g_strings[k].string;
        for (j = 0; j < n; j++)
            size += (unsigned)strlen(have[j]) + 1;
        if ((list = (unsigned char *)malloc(size)) == 0)
            continue;
        o = list;
        *o++ = (unsigned char)n;
        for (j = 0; j < n; j++) {
            strcpy((char *)o, have[j]);
            o += strlen(have[j]) + 1;
        }
        set_text(c, list, size, "a patch");
        free(list);
    }
}

static int(__cdecl *orig_File_Open)(const char *name, void *h);
static int __cdecl ev_File_Open(const char *name, void *h)
{
    return orig_File_Open(redirect(name), h);
}

static void *(__cdecl *orig_fopen)(const char *path, const char *mode);
static void *__cdecl ev_fopen(const char *path, const char *mode)
{
    return orig_fopen(mode && mode[0] == 'r' ? redirect(path) : path, mode);
}

static void *(WINAPI *orig_mmioOpenA)(char *name, void *info, DWORD flags);
static void *WINAPI ev_mmioOpenA(char *name, void *info, DWORD flags)
{
    if (name && !(flags & 0x00000003) && !(flags & 0x00001000)) /* read-only: not MMIO_WRITE/READWRITE/CREATE */
        name = (char *)redirect(name);
    return orig_mmioOpenA(name, info, flags);
}

/* an imported function: its slot in the import table takes the replacement */
static int hook_import(const char *name, void *replacement, void **original)
{
    char sym[96];
    void **slot;
    DWORD old;
    _snprintf(sym, sizeof sym, "__imp_%s", name);
    slot = (void **)api_find(sym);
    if (!slot || !VirtualProtect(slot, sizeof *slot, PAGE_READWRITE, &old)) {
        log_line("cannot redirect the import %s", name);
        return -1;
    }
    *original = *slot;
    *slot = replacement;
    VirtualProtect(slot, sizeof *slot, old, &old);
    return 0;
}

/* whether a mod's level patch takes sounds from another level (so the .SND files go through content_file) */
static int mods_take_sounds(void)
{
    int i;
    for (i = 0; i < g_nMods; i++) {
        char pat[MAX_PATH], file[MAX_PATH], level[64];
        WIN32_FIND_DATAA fd;
        HANDLE h;
        _snprintf(pat, sizeof pat, "%slevels\\*.txt", g_modDirs[i]);
        if ((h = FindFirstFileA(pat, &fd)) == INVALID_HANDLE_VALUE)
            continue;
        do {
            char *text;
            _snprintf(file, sizeof file, "%slevels\\%s", g_modDirs[i], fd.cFileName);
            if ((text = read_text(file)) != 0) {
                const char *s = text;
                unsigned long id;
                int any = next_sound_line(&s, &id, level, sizeof level);
                s = text;
                any = any || next_new_line(&s, level, sizeof level, &id);
                free(text);
                if (any) {
                    FindClose(h);
                    return 1;
                }
            }
        } while (FindNextFileA(h, &fd));
        FindClose(h);
    }
    return 0;
}

/* ---- the Mods menu: a "Mods" button on the launcher's first screen (under "Clear saves and config", made by the
 * game's own Launcher_MakeButtonBitmap so that it looks like the others) opens a list of the installed mods, with
 * their name, version and description; unticking one writes it to Mods\disabled.txt. Mods load when the game starts,
 * before the launcher (some must hook what the game sets up first), so a change applies from the next start. */
#define IDC_SDW_MODS 1190
#define IDC_SDW_OK 1191
#define IDC_SDW_CANCEL 1192
#define IDC_SDW_MOD0 1200
#define IDB_BTN_CLEAR 0x93
static HWND g_modsMenu;
static int g_modsMenuOpen;

static void mods_menu_save(HWND w)
{
    char path[MAX_PATH];
    FILE *f;
    int i, off = 0;
    _snprintf(path, sizeof path, "%sMods\\disabled.txt", g_gameDir);
    for (i = 0; i < g_nModInfo; i++)
        off += SendDlgItemMessageA(w, IDC_SDW_MOD0 + i, BM_GETCHECK, 0, 0) != BST_CHECKED;
    if (!off) {
        DeleteFileA(path);
        return;
    }
    if (!(f = fopen(path, "w")))
        return;
    fprintf(f, "# the mods the Mods menu switched off (their folder names)\n");
    for (i = 0; i < g_nModInfo; i++)
        if (SendDlgItemMessageA(w, IDC_SDW_MOD0 + i, BM_GETCHECK, 0, 0) != BST_CHECKED)
            fprintf(f, "%s\n", g_modInfo[i].folder);
    fclose(f);
}

static LRESULT CALLBACK mods_menu_proc(HWND w, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
        case WM_COMMAND:
            if (LOWORD(wp) == IDC_SDW_OK)
                mods_menu_save(w);
            if (LOWORD(wp) == IDC_SDW_OK || LOWORD(wp) == IDC_SDW_CANCEL)
                DestroyWindow(w);
            return 0;
        case WM_CLOSE:
            DestroyWindow(w);
            return 0;
        case WM_DESTROY:
            g_modsMenuOpen = 0;
            return 0;
    }
    return DefWindowProcA(w, msg, wp, lp);
}

static HWND mods_menu_control(HWND parent, const char *cls, const char *text, DWORD style, int x, int y, int cx, int cy,
                              int id, HFONT font)
{
    HWND c = CreateWindowExA(0, cls, text, WS_CHILD | WS_VISIBLE | style, x, y, cx, cy, parent, (HMENU)(size_t)id,
                             GetModuleHandleA(0), 0);
    SendMessageA(c, WM_SETFONT, (WPARAM)font, 1);
    return c;
}

static void show_mods_menu(HWND owner)
{
    static int registered;
    HFONT font = (HFONT)GetStockObject(DEFAULT_GUI_FONT);
    RECT o, frame;
    MSG msg;
    int i, y = 40, width = 460, height;
    if (!registered) {
        WNDCLASSA wc;
        memset(&wc, 0, sizeof wc);
        wc.lpfnWndProc = mods_menu_proc;
        wc.hInstance = GetModuleHandleA(0);
        wc.hCursor = LoadCursorA(0, IDC_ARROW);
        wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
        wc.lpszClassName = "SdwModsMenu";
        registered = RegisterClassA(&wc) != 0;
    }
    height = 40 + g_nModInfo * 46 + 50;
    SetRect(&frame, 0, 0, width, height);
    AdjustWindowRect(&frame, WS_POPUP | WS_CAPTION | WS_SYSMENU, 0);
    GetWindowRect(owner, &o);
    g_modsMenu = CreateWindowExA(WS_EX_DLGMODALFRAME, "SdwModsMenu", "Mods", WS_POPUP | WS_CAPTION | WS_SYSMENU,
                                 o.left + (o.right - o.left - (frame.right - frame.left)) / 2,
                                 o.top + (o.bottom - o.top - (frame.bottom - frame.top)) / 2, frame.right - frame.left,
                                 frame.bottom - frame.top, owner, 0, GetModuleHandleA(0), 0);
    if (!g_modsMenu)
        return;
    mods_menu_control(g_modsMenu, "STATIC",
                      g_nModInfo ? "Tick the mods to use. A change applies the next time the game starts."
                                 : "No mods are installed: a mod is a folder in Mods (MODDING.md).",
                      0, 12, 12, width - 24, 20, -1, font);
    for (i = 0; i < g_nModInfo; i++, y += 46) {
        ModInfo *m = &g_modInfo[i];
        char label[160], note[400];
        _snprintf(label, sizeof label, "%s%s%s", m->name, m->version[0] ? "   " : "", m->version);
        _snprintf(note, sizeof note, "%s%s%s", m->description[0] ? m->description : "(no description: mod.txt)",
                  !m->switchedOff && m->disabled ? "   Not loaded now: see Mods\\mods.log." : "",
                  m->author[0] ? "" : "");
        mods_menu_control(g_modsMenu, "BUTTON", label, BS_AUTOCHECKBOX | WS_TABSTOP, 12, y, width - 24, 18,
                          IDC_SDW_MOD0 + i, font);
        SendDlgItemMessageA(g_modsMenu, IDC_SDW_MOD0 + i, BM_SETCHECK, m->switchedOff ? BST_UNCHECKED : BST_CHECKED, 0);
        mods_menu_control(g_modsMenu, "STATIC", note, 0, 30, y + 19, width - 42, 24, -1, font);
    }
    mods_menu_control(g_modsMenu, "BUTTON", "OK", BS_DEFPUSHBUTTON | WS_TABSTOP, width - 184, height - 38, 80, 26,
                      IDC_SDW_OK, font);
    mods_menu_control(g_modsMenu, "BUTTON", "Cancel", BS_PUSHBUTTON | WS_TABSTOP, width - 96, height - 38, 80, 26,
                      IDC_SDW_CANCEL, font);
    ShowWindow(g_modsMenu, SW_SHOW);
    EnableWindow(owner, 0);
    g_modsMenuOpen = 1;
    while (g_modsMenuOpen && GetMessageA(&msg, 0, 0, 0) > 0)
        if (!IsDialogMessageA(g_modsMenu, &msg)) {
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
    EnableWindow(owner, 1);
    SetForegroundWindow(owner);
}

typedef HBITMAP(__cdecl *MakeButtonBitmapFn)(HWND dialog, const char *bitmap, const char *text, unsigned color);
static INT_PTR(__stdcall *orig_Launcher_MainDlgProc)(HWND, UINT, WPARAM, LPARAM);
static INT_PTR __stdcall ev_Launcher_MainDlgProc(HWND w, UINT msg, WPARAM wp, LPARAM lp)
{
    INT_PTR r;
    if (msg == WM_COMMAND && LOWORD(wp) == IDC_SDW_MODS) {
        show_mods_menu(w);
        return 1;
    }
    r = orig_Launcher_MainDlgProc(w, msg, wp, lp);
    if (msg == WM_INITDIALOG) { /* under "Clear saves and config" (dialog units 16, 198, 178 x 15) */
        MakeButtonBitmapFn make = (MakeButtonBitmapFn)api_find("Launcher_MakeButtonBitmap");
        RECT box;
        HWND button;
        SetRect(&box, 16, 216, 16 + 178, 216 + 15);
        MapDialogRect(w, &box);
        button = CreateWindowExA(0, "BUTTON", "Mods", WS_CHILD | WS_VISIBLE | WS_TABSTOP | (make ? BS_BITMAP : 0),
                                 box.left, box.top, box.right - box.left, box.bottom - box.top, w,
                                 (HMENU)(size_t)IDC_SDW_MODS, GetModuleHandleA(0), 0);
        if (make && button) {
            HBITMAP image = make(w, MAKEINTRESOURCEA(IDB_BTN_CLEAR), "Mods", 0);
            if (image)
                SendMessageA(button, BM_SETIMAGE, IMAGE_BITMAP, (LPARAM)image);
        }
    }
    return r;
}

static void content_hooks(void)
{
    InitializeCriticalSection(&g_contentLock);
    g_pathSlot = TlsAlloc();
    api_hook("Launcher_MainDlgProc", (void *)ev_Launcher_MainDlgProc, (void **)&orig_Launcher_MainDlgProc);
    if (mods_have("levels")) {
        api_hook("Load_WAR", (void *)ev_Load_WAR, (void **)&orig_Load_WAR);
        api_hook("malloc", (void *)ev_malloc, (void **)&orig_malloc);
        api_hook("Load_WarMeshes", (void *)ev_Load_WarMeshes, (void **)&orig_Load_WarMeshes);
        api_hook("Scenaric_RegisterClass_2", (void *)ev_Scenaric_RegisterClass_2, (void **)&orig_Scenaric_RegisterClass_2);
        api_hook("Render_RestoreLostSurfaces", (void *)ev_Render_RestoreLostSurfaces,
                 (void **)&orig_Render_RestoreLostSurfaces);
        hook_register_all();
    }
    if (mods_have("files") || mods_have("sounds") || mods_take_sounds()) {
        api_hook("File_Open", (void *)ev_File_Open, (void **)&orig_File_Open);
        api_hook("fopen", (void *)ev_fopen, (void **)&orig_fopen);
        hook_import("mmioOpenA", (void *)ev_mmioOpenA, (void **)&orig_mmioOpenA);
    }
}

static int(WINAPI *orig_WinMain)(HINSTANCE, HINSTANCE, LPSTR, int);
static int WINAPI loader_WinMain(HINSTANCE inst, HINSTANCE prev, LPSTR cmd, int show)
{
    load_mods();
    content_hooks();
    return orig_WinMain(inst, prev, cmd, show);
}

/* ---------------------------------------------------------------------------------------------------------- DLL */

static void start(void)
{
    char exe[MAX_PATH], logPath[MAX_PATH], sha[41] = "";
    char *slash;
    GetModuleFileNameA(0, exe, sizeof exe);
    lstrcpynA(g_gameDir, exe, sizeof g_gameDir);
    slash = strrchr(g_gameDir, '\\');
    if (slash)
        slash[1] = 0;
    _snprintf(logPath, sizeof logPath, "%sMods", g_gameDir);
    if (GetFileAttributesA(logPath) == INVALID_FILE_ATTRIBUTES)
        return; /* no Mods folder: nothing to do, and nothing written */
    _snprintf(logPath, sizeof logPath, "%sMods\\mods.log", g_gameDir);
    g_log = fopen(logPath, "w");
    log_line("SDW mod loader, API %d; exe %s", SDW_MOD_API_VERSION, exe);
    if (!sha1_file(exe, sha)) {
        log_line("cannot read the exe: no mods");
        return;
    }
    if (!strcmp(sha, "ca39374d53ae0030c5bd8c90dda45465e446dfe3"))
        g_gameName = "SheepD3D PAL";
    else if (!strcmp(sha, "bc2b4a7ffa970b60d4601997979aa7d0b62d44c4")) /* a widescreen-patched build: the same */
        g_gameName = "SheepD3D PAL, widescreen build";                 /* addresses, 83 bytes of .text differ */
    else if (load_translation(exe, sha)) /* a build of the source with its own addresses (tools/build_fixed.py) */
        g_gameName = "SheepD3D built from the source, with its own symbol file";
    else {
        log_line("SHA-1 %s is not the PAL SheepD3D.exe this loader knows, and there is no symbol file for it beside it: "
                 "no mods", sha);
        return;
    }
    log_line("%s (SHA-1 %s)", g_gameName, sha);
    if (api_hook("WinMain", (void *)loader_WinMain, (void **)&orig_WinMain) != 0)
        log_line("cannot hook WinMain: no mods");
}

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID reserved)
{
    (void)inst;
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(inst);
        start();
    }
    return TRUE;
}

/* the one DINPUT8 export the game imports, forwarded to the system's dinput8.dll */
HRESULT WINAPI DirectInput8Create(HINSTANCE inst, DWORD version, REFIID iid, LPVOID *out, LPUNKNOWN outer)
{
    static HRESULT(WINAPI * real)(HINSTANCE, DWORD, REFIID, LPVOID *, LPUNKNOWN);
    if (!real) {
        char path[MAX_PATH];
        HMODULE dll;
        GetSystemDirectoryA(path, sizeof path);
        lstrcatA(path, "\\dinput8.dll");
        dll = LoadLibraryA(path);
        if (dll)
            real = (HRESULT(WINAPI *)(HINSTANCE, DWORD, REFIID, LPVOID *, LPUNKNOWN))GetProcAddress(
                dll, "DirectInput8Create");
        if (!real) {
            log_line("the system dinput8.dll could not be loaded from %s", path);
            return E_FAIL;
        }
    }
    return real(inst, version, iid, out, outer);
}
