#include "sdw_enums.h"
#include "../sdk/dinput.h"


#define SDW_MEMBERS_InputDevice InputDevice();                                  /* 0x403f30 InputDevice_Construct */
#define SDW_MEMBERS_Mouse Mouse(u16 buttonCount, D3DApp *app, HRESULT *result); /* 0x409e90 Mouse_Construct */
#include "sdw_classes.h"
#include "../sdk/crt.h"
#include "../sdk/win32.h"

/* ======================================================================== Mouse (0x409e90-0x40a13d) */

/* 0x409e90 - at most 4 buttons; the system mouse, exclusive foreground. *result is the first failing HRESULT. */
Mouse::Mouse(u16 buttonCount, D3DApp *app, HRESULT *result)
{
    if (buttonCount > 4)
        AllocButtons(4, app);
    else
        AllocButtons(buttonCount, app);
    deviceKind = INPUTDEV_MOUSE;
    isDigital = 0;
    *result = pApp->CreateMouseDevice(&pDevice);
    if (*result >= 0) {
        *result = pDevice->SetDataFormat(&c_dfDIMouse);
        if (*result >= 0)
            *result = pDevice->SetCooperativeLevel(pApp->hWnd, DISCL_EXCLUSIVE | DISCL_FOREGROUND);
    }
}

/* 0x409f4f */
Mouse::~Mouse()
{
    if (pDevice) {
        pDevice->Unacquire();
        pDevice->Release();
        pDevice = NULL;
    }
}

/* 0x409fa2 - acquired follows the request even when Acquire fails (its HRESULT is ignored). */
long Mouse::SetAcquired(u8 acquire)
{
    if (pDevice == NULL)
        return E_FAIL;
    if (acquire == 1) {
        pDevice->Acquire();
        acquired = 1;
    } else {
        pDevice->Unacquire();
        acquired = 0;
    }
    return 0;
}

/* 0x409ffe - GetDeviceState, re-acquiring while the input is lost; the axes (relative mickeys) are rounded toward minus
 * infinity to a multiple of 8, the buttons are the high bits of rgbButtons. */
long Mouse::Update()
{
    DIMOUSESTATE state;
    long res;
    u8 i;

    if (pDevice != NULL && acquired == 1) {
        res = DIERR_INPUTLOST;
        while (res == DIERR_INPUTLOST) {
            res = pDevice->GetDeviceState(sizeof(DIMOUSESTATE), &state);
            if (res == DIERR_INPUTLOST) {
                res = pDevice->Acquire();
                if (res < 0)
                    return res;
            }
        }
        if (res < 0)
            return res;
        rawX = (state.lX >> 3) << 3;
        rawY = (state.lY >> 3) << 3;
        rawZ = (state.lZ >> 3) << 3;
        for (i = 0; i < buttonCount; i++)
            buttonDown[i] = (state.rgbButtons[i] & 0x80) ? 1 : 0;
        InputDevice::Update();
        return 0;
    }
    return E_FAIL;
}

/* 0x40a110 Mouse_ScalarDeletingDtor: generated by the compiler from the virtual destructor. */
