/*
 * Object T002 (data/tu_map.json), guessed original file InputDevice.cpp.
 *   .text 0x403f30-0x40448c, then the COMDAT ??_GInputDevice 0x404490-0x4044be
 *   .rdata 0x5742d0-0x5742e8: the vtable, then the float constants 1.0f, -1.0f, 65535.0f (the first game .rdata)
 * The DirectInput device base class. The Joystick is T005 (src/app/joystick.cpp), GetObjectName and the Keyboard are
 * T006 (src/app/keyboard.cpp); the shared declarations are in input_device.h next to this file.
 */
#include "input_device.h"
#include "sdw_enums.h"

/* ======================================================================== InputDevice, 0x403f30-0x4044bf */

/* 0x403f30 */
InputDevice::InputDevice()
{
    acquired = 0;
    deviceKind = INPUTDEV_JOYSTICK;
    isDigital = 1;
    allowHeld = 1;
}

/* 0x403f63 - frees the four button arrays. */
InputDevice::~InputDevice()
{
    if (buttonDown)
        delete buttonDown;
    if (buttonPressed)
        delete buttonPressed;
    if (buttonBlocked)
        delete buttonBlocked;
    if (buttonDownPrev)
        delete buttonDownPrev;
}

/* 0x403ff1 - allocates and clears the button arrays (at most 0x100 buttons) and resets the axes and their calibration. */
void InputDevice::AllocButtons(u16 count, D3DApp *app)
{
    u16 i;
    if (count > 0x100)
        buttonCount = 0x100;
    else
        buttonCount = count;
    buttonDown = new u8[buttonCount];
    buttonPressed = new u8[buttonCount];
    buttonBlocked = new u8[buttonCount];
    buttonDownPrev = new u8[buttonCount];
    axisZ = 0.0f;
    axisY = 0.0f;
    axisX = 0.0f;
    rawZ = 0;
    rawY = 0;
    rawX = 0;
    memset(buttonPressed, 0, buttonCount);
    memset(buttonDown, 0, buttonCount);
    axisScaleZ = 1.0f;
    axisScaleY = 1.0f;
    axisScaleX = 1.0f;
    axisOffsetZ = 0.0f;
    axisOffsetY = 0.0f;
    axisOffsetX = 0.0f;
    for (i = 0; i < buttonCount; i++) {
        buttonDownPrev[i] = 0;
        buttonBlocked[i] = 0;
    }
    pApp = app;
}

/* 0x404185 - the base device has nothing to acquire. */
long InputDevice::SetAcquired(u8 acquire)
{
    return 0;
}

/* 0x404194 - axes from the raw values, and buttonPressed from buttonDown (see the file comment). */
long InputDevice::Update()
{
    u16 i;
    axisX = rawX / 65535.0f;
    if (axisX < -1.0f)
        axisX = -1.0f;
    else if (axisX > 1.0f)
        axisX = 1.0f;
    axisY = rawY / 65535.0f;
    if (axisY < -1.0f)
        axisY = -1.0f;
    else if (axisY > 1.0f)
        axisY = 1.0f;
    axisZ = rawZ / 65535.0f;
    if (axisZ < -1.0f)
        axisZ = -1.0f;
    else if (axisZ > 1.0f)
        axisZ = 1.0f;
    axisX = axisX * axisScaleX + axisOffsetX;
    axisY = axisY * axisScaleY + axisOffsetY;
    axisZ = axisZ * axisScaleZ + axisOffsetZ;
    for (i = 0; i < buttonCount; i++) {
        buttonPressed[i] = (buttonDown[i] && !buttonBlocked[i] && (!buttonDownPrev[i] || allowHeld)) ? 1 : 0;
        buttonDownPrev[i] = buttonDown[i];
    }
    return 0;
}

/* 0x40437e */
void InputDevice::SetAxisCalibration(float sx, float sy, float sz, float ox, float oy, float oz)
{
    axisScaleX = sx;
    axisScaleY = sy;
    axisScaleZ = sz;
    axisOffsetX = ox;
    axisOffsetY = oy;
    axisOffsetZ = oz;
}

/* 0x4043c1 */
void InputDevice::GetAxisCalibration(float *sx, float *sy, float *sz, float *ox, float *oy, float *oz)
{
    *sx = axisScaleX;
    *sy = axisScaleY;
    *sz = axisScaleZ;
    *ox = axisOffsetX;
    *oy = axisOffsetY;
    *oz = axisOffsetZ;
}

/* 0x404410 - the indices of the buttons pressed this frame, at most maxCount of them; returns how many. No callers. */
u16 InputDevice::GetPressedButtons(u16 *out, u16 maxCount)
{
    u16 i = 0;
    u16 n = 0;
    u16 *dst = out;
    while (i < buttonCount && n < maxCount) {
        if (buttonPressed[i] == 1) {
            dst[n] = i;
            n++;
        }
        i++;
    }
    return n;
}

/* 0x404490 InputDevice_ScalarDeletingDtor: generated by the compiler from the virtual destructor. */
