/*
 * Object T005 (data/tu_map.json), guessed original file Joystick.cpp.
 *   .text 0x406db0-0x40717c, then the COMDAT ??_GJoystick 0x407180-0x4071ae
 *   .rdata 0x574308-0x574314 (the vtable)       .bss 0x5c7a9c-0x5c7aa0 (g_pEnumJoystickDevice)
 * Defines g_pEnumJoystickDevice. Shared declarations: input_device.h next to this file.
 */
#include "input_device.h"
#include "sdw_enums.h"
#include "../sdk/dinput.h"

IDirectInputDevice8A *g_pEnumJoystickDevice; /* 0x5c7a9c  the device DI_JoystickAxisEnumCallback configures */

/* ======================================================================== Joystick, 0x406db0-0x4071af */

/* 0x406db0 - at most 0x20 buttons; creates the device for the controller chosen in the launcher, exclusive foreground,
 * and sets every axis's range to +-0xffff (DI_JoystickAxisEnumCallback). *result is the first failing HRESULT. */
Joystick::Joystick(u16 buttonCount, D3DApp *app, HRESULT *result)
{
    if (buttonCount > 0x20)
        AllocButtons(0x20, app);
    else
        AllocButtons(buttonCount, app);
    deviceKind = INPUTDEV_JOYSTICK;
    *result = pApp->CreateJoystickDevice(&pDevice);
    if (*result >= 0) {
        *result = pDevice->SetDataFormat(&c_dfDIJoystick);
        if (*result >= 0) {
            *result = pDevice->SetCooperativeLevel(pApp->hWnd, DISCL_EXCLUSIVE | DISCL_FOREGROUND);
            if (*result >= 0) {
                JOY_CAPS.dwSize = sizeof(DIDEVCAPS);
                *result = pDevice->GetCapabilities(&JOY_CAPS);
                isDigital = 0;
                g_pEnumJoystickDevice = pDevice;
                pDevice->EnumObjects(DI_JoystickAxisEnumCallback, pApp->hWnd, DIDFT_AXIS);
            }
        }
    }
}

/* 0x406ed6 */
Joystick::~Joystick()
{
    if (pDevice) {
        pDevice->Unacquire();
        pDevice->Release();
        pDevice = NULL;
    }
}

/* 0x406f29 - acquired follows the request even when Acquire fails (its HRESULT is ignored). */
long Joystick::SetAcquired(u8 acquire)
{
    if (pDevice == NULL)
        return E_FAIL;
    if (acquire == 1) {
        pDevice->Acquire();
        acquired = 1;
    } else {
        pDevice->Unacquire();
        acquired = 0;
    }
    return 0;
}

/* 0x406f85 - Poll + GetDeviceState, re-acquiring while the input is lost; the axes are clamped to +-0xffff and rounded
 * down to a multiple of 8, the buttons are the high bits of rgbButtons. */
long Joystick::Update()
{
    DIJOYSTATE state;
    long res;
    u8 i;
    s32 j;
    s32 axes[3];

    if (pDevice != NULL && acquired == 1) {
        res = DIERR_INPUTLOST;
        while (res == DIERR_INPUTLOST) {
            res = pDevice->Poll();
            if (res < 0)
                return res;
            res = pDevice->GetDeviceState(sizeof(DIJOYSTATE), &state);
            if (res == DIERR_INPUTLOST) {
                res = pDevice->Acquire();
                if (res < 0)
                    return res;
            }
        }
        if (res < 0)
            return res;
        axes[0] = state.lX;
        axes[1] = state.lY;
        axes[2] = state.lZ;
        for (j = 0; j < 3; j++) {
            if (axes[j] < -0xffff)
                axes[j] = -0xffff;
            else if (axes[j] > 0xffff)
                axes[j] = 0xffff;
        }
        rawX = (axes[0] >> 3) << 3;
        rawY = (axes[1] >> 3) << 3;
        rawZ = (axes[2] >> 3) << 3;
        for (i = 0; i < buttonCount; i++)
            buttonDown[i] = (state.rgbButtons[i] & 0x80) ? 1 : 0;
        InputDevice::Update();
        return 0;
    }
    return E_FAIL;
}

/* 0x407116 - EnumObjects callback for the joystick's axes: range -0xffff..0xffff. Stops the enumeration on failure. */
BOOL __stdcall DI_JoystickAxisEnumCallback(const DIDEVICEOBJECTINSTANCEA *doi, void *ref)
{
    BOOL ret;
    DIPROPRANGE diprg;
    diprg.diph.dwSize = sizeof(DIPROPRANGE);
    diprg.diph.dwHeaderSize = sizeof(DIPROPHEADER);
    diprg.diph.dwHow = DIPH_BYID;
    diprg.diph.dwObj = doi->dwType;
    diprg.lMin = -0xffff;
    diprg.lMax = 0xffff;
    if (g_pEnumJoystickDevice->SetProperty(DIPROP_RANGE, &diprg.diph) < 0)
        ret = DIENUM_STOP;
    else
        ret = DIENUM_CONTINUE;
    return ret;
}

/* 0x407180 Joystick_ScalarDeletingDtor: generated by the compiler from the virtual destructor. */
