#!/usr/bin/env python3
"""Convert the disc's Scenaric_Classes.h (#define offsets) into real C types.

Input : Levels/Lvl-03/Scenaric_Classes.h  (197 classes, every property a 4-byte slot)
        Levels/Lvl-03/GameRes.h           (the ids of the exported resources, WAR_IDO_* and DAV_IDI_*)
Output: src/include/scenaric_props.h      (enum ScenaricClassId + enum GameResId + struct <Class>Props per class)
        work/scenaric_classes.json        (machine-readable schema for other tools)

Property types are unknown at this stage, so every slot is a u32. Retype fields in the
generated header's OVERRIDES table as the code reveals them (float, object id, box id...).
"""
import textio  # noqa: F401  (first: UTF-8, LF text files on Windows)
import json
import re
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "Sheep, Dog 'n' Wolf (PAL Version)" / "Levels" / "Lvl-03" / "Scenaric_Classes.h"
GAMERES = SRC.with_name("GameRes.h")
OUT_H = ROOT / "src" / "include" / "scenaric_props.h"
OUT_JSON = ROOT / "work" / "scenaric_classes.json"

# (CLASSMACRO, FIELD) -> C type, filled in as fields are understood. Must stay 4 bytes wide.
OVERRIDES = {}

C_KEYWORDS = {"case", "default", "switch", "int", "float", "long", "short", "char", "double", "register", "auto"}


def parse(text):
    classes = []
    blocks = re.split(r'/{6,}Definition of class "', text)[1:]
    for b in blocks:
        name = b[:b.index('"')]
        cid = re.search(r"#define CLASSID_(\w+)\s+(\d+)", b)
        macro, class_id = cid.group(1), int(cid.group(2))
        size = int(re.search(r"#define PROPSIZE_%s\s+(\d+)" % re.escape(macro), b).group(1))
        props = [(m.group(1), int(m.group(2)))
                 for m in re.finditer(r"#define PROPERTY_%s_(\w+)\s+(\d+)" % re.escape(macro), b)]
        props.sort(key=lambda p: p[1])
        classes.append({"name": name, "macro": macro, "id": class_id, "size": size,
                        "props": [{"name": n, "offset": o} for n, o in props]})
    return classes


def ident(s):
    s = re.sub(r"\W", "_", s)
    if s[0].isdigit() or s.lower() in C_KEYWORDS:
        s = "_" + s
    return s


def emit(classes):
    out = ["// GENERATED by tools/scenaric_to_c.py from the disc's Scenaric_Classes.h - do not edit by hand.",
           "// Property blocks of scenaric object instances as stored in .WAR files.",
           "#ifndef SCENARIC_PROPS_H", "#define SCENARIC_PROPS_H", "",
           "typedef unsigned int u32;", "",
           "typedef enum ScenaricClassId {"]
    for c in classes:
        out.append("    CLASSID_%s = %d,%s" % (c["macro"], c["id"], "" if c["macro"].lower() == ident(c["name"]).lower()
                                                 else "  // \"%s\"" % c["name"]))
    out += ["    CLASSID_COUNT = %d," % len(classes),
            "    CLASSID_NONE = 0xffff  // not in the disc header: 'no class' (Scenaric_CreateObject, the inventory selection, "
            "CannonBall.hitClassId, the Map lists)",
            "} ScenaricClassId;", ""]
    ids = [(m.group(1), int(m.group(2))) for m in
           re.finditer(r"#define\s+((?:WAR|DAV)_ID\w_\w+)\s+(\d+)", GAMERES.read_text(encoding="latin-1"))]
    out.append("// GameRes.h: ids of the resources exported by the level files (WAR_IDO_* objects and boxes, DAV_IDI_* images)")
    out.append("typedef enum GameResId {")
    out += ["    %s = %d," % (n, v) for n, v in ids]
    out += ["} GameResId;", ""]

    for c in classes:
        sname = ident(c["name"].replace(" ", "")) + "Props"
        out.append("// class \"%s\" (id %d), PROPSIZE %d" % (c["name"], c["id"], c["size"]))
        if not c["size"]:
            out += ["// (no properties)", ""]
            continue
        out.append("typedef struct %s {" % sname)
        cur, pad = 0, 0
        for p in c["props"]:
            if p["offset"] > cur:
                out.append("    u32 _pad%d[%d];" % (pad, (p["offset"] - cur) // 4))
                pad += 1
            ctype = OVERRIDES.get((c["macro"], p["name"]), "u32")
            out.append("    %-5s %-28s // +0x%02x" % (ctype, ident(p["name"]) + ";", p["offset"]))
            cur = p["offset"] + 4
        if c["size"] > cur:
            out.append("    u32 _pad%d[%d];" % (pad, (c["size"] - cur) // 4))
        out += ["} %s;" % sname, ""]
    out.append("#endif")
    return "\n".join(out) + "\n"


def main():
    classes = parse(SRC.read_text(encoding="latin-1"))
    for c in classes:  # sanity: no overlaps, nothing past PROPSIZE
        offs = [p["offset"] for p in c["props"]]
        assert len(set(offs)) == len(offs), c["name"]
        assert all(o + 4 <= c["size"] for o in offs), c["name"]
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(emit(classes))
    OUT_JSON.parent.mkdir(exist_ok=True)
    OUT_JSON.write_text(json.dumps(classes, indent=1))
    gaps = sum(1 for c in classes if c["size"] != 4 * len(c["props"]))
    print("%d classes, %d properties, %d classes with padding gaps -> %s" % (
        len(classes), sum(len(c["props"]) for c in classes), gaps, OUT_H.relative_to(ROOT)))


if __name__ == "__main__":
    main()
