// GENERATED by tools/structs_to_c.py - basic types of the decompilation.
#ifndef SDW_TYPES_H
#define SDW_TYPES_H
typedef signed char s8;
typedef unsigned char u8;
typedef short s16;
typedef unsigned short u16;
typedef int s32;
typedef unsigned int u32;
#ifdef _MSC_VER                                                    /* VC6 has no long long */
typedef __int64 s64;
typedef unsigned __int64 u64;
#else
typedef long long s64;
typedef unsigned long long u64;
#endif
typedef void (*fnptr)(void);
#ifdef _MSC_VER
#define SDW_CDECL __cdecl
#else
#define SDW_CDECL
#endif
typedef struct Vec3s { s16 x, y, z; } Vec3s;                 // vertical axis points DOWN
typedef struct Box { u32 flags; s16 min[3]; s16 max[3];          // zone / trigger / model box as stored in WAR files
#if defined(__cplusplus) && defined(SDW_MEMBERS_Box)
    SDW_MEMBERS_Box                                                 // member functions only (Box_ContainsPointXZ 0x4486c0 is a thiscall)
#endif
} Box;
#endif
